const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const enrichments = {
  'poplars-on-the-epte-portland': {
    description: `<p><a href="/apps/masterpieces/artist/claude-monet"><strong>Claude Monet</strong></a> painted this row of poplar trees along the Epte River in 1891, the same year he completed his Grainstacks series. The tall, slender trunks rise like columns, their foliage forming a rhythmic pattern of <strong>green, gold, and sky</strong> reflected in the still water below.</p><p>Monet worked from a floating studio boat anchored on the Epte. When the local commune auctioned the poplars for timber, he paid a dealer to buy them on the condition they'd stay standing until he finished painting. He produced about 24 poplar canvases in total, studying the trees across different seasons and times of day.</p><p>This version hangs at the <a href="/apps/masterpieces/museum/portland-art-museum"><strong>Portland Art Museum</strong></a> in Oregon. The Poplars series, exhibited at Durand-Ruel's gallery in 1892, confirmed Monet's serial approach as the defining method of late <a href="/apps/masterpieces/movement/impressionism"><strong>Impressionism</strong></a>.</p>`,
    faqs: [
      { question: "Where can I see this painting?", answer: "This Poplars canvas is at the <a href=\"/apps/masterpieces/museum/portland-art-museum\"><strong>Portland Art Museum</strong></a> in Oregon. Other versions are in the Met, Philadelphia Museum of Art, and National Museum of Western Art in Tokyo." },
      { question: "How many Poplars paintings did Monet make?", answer: "<a href=\"/apps/masterpieces/artist/claude-monet\"><strong>Monet</strong></a> painted about <strong>24 poplar canvases</strong> in 1891. He worked from a boat on the Epte River and even paid to delay the trees' auction so he could finish painting them." },
      { question: "Where is the Epte River?", answer: "The <strong>Epte</strong> flows through Normandy near Monet's home at Giverny. It marked the historic border between Normandy and the Île-de-France, and its poplar-lined banks gave Monet one of his most iconic series subjects." }
    ]
  },
  'renoir-after-bath-houston': {
    description: `<p><a href="/apps/masterpieces/artist/pierre-auguste-renoir"><strong>Pierre-Auguste Renoir</strong></a> painted this nude in 1888 during his "dry" or "Ingres" period, when he temporarily abandoned the soft brushwork of <a href="/apps/masterpieces/movement/impressionism"><strong>Impressionism</strong></a> for firmer drawing and sculptural form. A young woman dries herself after bathing, her skin rendered with <strong>warm pinks and pearly whites</strong> against a loosely painted landscape background.</p><p>Renoir's bathers of this period show his admiration for Ingres and Raphael. He'd traveled to Italy in 1881 and returned convinced that Impressionism had reached a dead end. The tighter modeling of flesh and clearer outlines here reflect that crisis of confidence, though his palette stayed characteristically warm and luminous.</p><p>The painting belongs to the <a href="/apps/masterpieces/museum/museum-of-fine-arts-houston"><strong>Museum of Fine Arts, Houston</strong></a>. By the 1890s, Renoir had relaxed back into a softer, more fluid style that merged his classical interests with Impressionist color.</p>`,
    faqs: [
      { question: "Where can I see this painting?", answer: "It hangs at the <a href=\"/apps/masterpieces/museum/museum-of-fine-arts-houston\"><strong>Museum of Fine Arts, Houston</strong></a>. The museum holds a strong collection of <a href=\"/apps/masterpieces/movement/impressionism\"><strong>Impressionist</strong></a> works." },
      { question: "What is Renoir's 'dry period'?", answer: "After visiting Italy in 1881, <a href=\"/apps/masterpieces/artist/pierre-auguste-renoir\"><strong>Renoir</strong></a> adopted <strong>firmer drawing and classical modeling</strong>, moving away from Impressionist softness. This phase lasted roughly from 1883 to 1890." },
      { question: "Why did Renoir paint so many bathers?", answer: "Renoir considered the <strong>female nude</strong> the highest subject in painting. He painted bathers throughout his career, treating the theme with increasing warmth and freedom as he aged." }
    ]
  },
  'homer-wreck-carnegie': {
    description: `<p><a href="/apps/masterpieces/artist/winslow-homer"><strong>Winslow Homer</strong></a> painted The Wreck in 1896 from his studio at Prouts Neck, Maine, where he spent his final decades observing the Atlantic coast. Rescue workers haul a survivor from the surf on a <strong>breeches buoy line</strong>, their figures braced against wind and spray. The sea dominates: dark, churning, indifferent.</p><p>Homer witnessed real shipwrecks along the Maine coast and knew the U.S. Life-Saving Service crews who responded to them. His late seascapes strip away narrative detail to focus on the raw confrontation between humans and the ocean. The palette is muted: grays, greens, and the cold white of breaking waves.</p><p>The painting hangs at the <a href="/apps/masterpieces/museum/carnegie-museum-of-art"><strong>Carnegie Museum of Art</strong></a> in Pittsburgh. Homer's late marine paintings, produced in near-solitude at Prouts Neck, are widely considered his greatest work and among the finest American paintings of the 19th century.</p>`,
    faqs: [
      { question: "Where can I see The Wreck?", answer: "It hangs at the <a href=\"/apps/masterpieces/museum/carnegie-museum-of-art\"><strong>Carnegie Museum of Art</strong></a> in Pittsburgh, Pennsylvania. The museum holds several important American paintings from the late 19th century." },
      { question: "Where did Homer paint his seascapes?", answer: "<a href=\"/apps/masterpieces/artist/winslow-homer\"><strong>Homer</strong></a> worked from a converted stable at <strong>Prouts Neck, Maine</strong>, overlooking the Atlantic. He lived there in near-seclusion from 1883 until his death in 1910." },
      { question: "What is a breeches buoy?", answer: "A <strong>breeches buoy</strong> is a rescue device: a life ring with canvas pants attached, pulled along a rope line from ship to shore. Homer painted the U.S. Life-Saving Service using this equipment in real coastal rescues." }
    ]
  },
  'hopper-cape-cod-morning-carnegie': {
    description: `<p><strong>Edward Hopper</strong> painted Cape Cod Morning in 1950, showing a woman leaning out of a bay window of a white clapboard house, gazing intently at something outside the frame. Bright morning sunlight hits the house's facade and the woman's face. Behind her, the room is dark. A strip of <strong>dense green foliage</strong> fills the middle ground.</p><p>Hopper and his wife Jo spent summers in Truro on Cape Cod from 1930 onward, and the local architecture appears throughout his work. The woman's pose suggests anticipation or longing, but Hopper never explained his narratives. He said, "If I could say it in words, there would be no reason to paint." The tension between what's visible and what's hidden drives the image.</p><p>The painting hangs at the <a href="/apps/masterpieces/museum/carnegie-museum-of-art"><strong>Carnegie Museum of Art</strong></a> in Pittsburgh. Hopper's Cape Cod paintings capture a specific quality of New England light: hard, clear, and isolating, even on a beautiful morning.</p>`,
    faqs: [
      { question: "Where can I see Cape Cod Morning?", answer: "It's at the <a href=\"/apps/masterpieces/museum/carnegie-museum-of-art\"><strong>Carnegie Museum of Art</strong></a> in Pittsburgh. The Carnegie holds this and other major American paintings from the 20th century." },
      { question: "Where on Cape Cod did Hopper paint?", answer: "Hopper and his wife Jo spent summers in <strong>Truro, Massachusetts</strong>, on the outer arm of Cape Cod. He built a studio there in 1934 and painted many of his most famous works from that location." },
      { question: "Who is the woman in the painting?", answer: "Hopper used his wife <strong>Jo</strong> as the model for nearly all his female figures. She posed for this painting at age 67, though Hopper typically made his models appear younger." }
    ]
  },
  'bougainvillier-calder-sam': {
    description: `<p><strong>Alexander Calder</strong> created Bougainvillier in 1947, a standing mobile of painted sheet metal and wire. Flat, biomorphic shapes in <strong>red, yellow, black, and white</strong> hang from thin wire arms, swaying gently with air currents. The title references the tropical bougainvillea flower, and the colored forms suggest petals floating in space.</p><p>Calder invented the mobile in the early 1930s after visiting Mondrian's studio and seeing how geometric shapes could create dynamic compositions. Marcel Duchamp coined the term "mobile" for Calder's kinetic sculptures. Each piece responds to its environment: a breeze, a viewer walking past, even the building's ventilation system changes the sculpture's configuration.</p><p>This work is in the collection of the <a href="/apps/masterpieces/museum/seattle-art-museum"><strong>Seattle Art Museum</strong></a>. Calder's mobiles transformed sculpture from a static, gravity-bound art into something closer to drawing in the air.</p>`,
    faqs: [
      { question: "Where can I see this Calder mobile?", answer: "Bougainvillier is at the <a href=\"/apps/masterpieces/museum/seattle-art-museum\"><strong>Seattle Art Museum</strong></a> in downtown Seattle. The museum holds several modern and contemporary sculptures." },
      { question: "How do Calder's mobiles work?", answer: "Calder's mobiles are <strong>balanced kinetic sculptures</strong> that move with air currents. He carefully calibrated the weight and position of each element so the entire structure shifts gracefully in response to its environment." },
      { question: "Who invented the term 'mobile'?", answer: "<strong>Marcel Duchamp</strong> coined the word \"mobile\" for Calder's moving sculptures in 1931. Jean Arp then suggested \"stabile\" for Calder's stationary works." }
    ]
  },
  'toile-araignee-calder': {
    description: `<p><strong>Alexander Calder</strong> made Toile d'araignée (Spider Web) in 1965, a late-career stabile of <strong>painted black steel</strong>. Unlike his floating mobiles, this sculpture is fixed and architectural, its angular steel plates bolted together to form a web-like structure that casts dramatic shadows. The title plays on the tension between industrial heaviness and the delicacy of a spider's web.</p><p>By the 1960s, Calder was producing monumental stabiles for public spaces worldwide. He worked with industrial fabricators to scale up his designs, translating the playfulness of his small studio pieces into steel forms weighing tons. The shift from wire and tin to welded plate steel changed the feel of his work without losing its sense of organic movement.</p><p>This piece is in the collection of the <a href="/apps/masterpieces/museum/seattle-art-museum"><strong>Seattle Art Museum</strong></a>. Calder's stabiles bridged fine art and architecture, appearing in plazas from Chicago to Paris.</p>`,
    faqs: [
      { question: "Where can I see this sculpture?", answer: "Toile d'araignée is at the <a href=\"/apps/masterpieces/museum/seattle-art-museum\"><strong>Seattle Art Museum</strong></a>. The museum's collection includes both modern and contemporary sculpture." },
      { question: "What is a stabile?", answer: "A <strong>stabile</strong> is a stationary abstract sculpture, as opposed to a mobile. Jean Arp coined the term to distinguish Calder's fixed works from his moving ones. Stabiles are typically made of welded or bolted metal." },
      { question: "What does the title mean?", answer: "\"<strong>Toile d'araignée</strong>\" is French for \"spider web.\" Calder often gave his works poetic titles that suggested natural forms, contrasting with the heavy industrial steel of the sculpture itself." }
    ]
  },
  'venetian-chihuly-tacoma': {
    description: `<p><strong>Dale Chihuly</strong> created this piece from his Venetians series in 1991. The series pays homage to the <strong>centuries-old glassblowing tradition of Murano, Italy</strong>, where Chihuly studied in 1968 on a Fulbright Fellowship. The forms are exuberant and organic: curling tendrils, flared lips, and vivid colors that push blown glass toward the scale and ambition of sculpture.</p><p>Chihuly lost sight in his left eye in a 1976 car accident and later dislocated his shoulder, making it impossible to hold the glass blowpipe himself. He transitioned to directing teams of glassblowers, sketching designs in bold colors and overseeing their execution. The collaborative process let him work at scales impossible for a single artist.</p><p>This Venetian is at the <a href="/apps/masterpieces/museum/tacoma-art-museum"><strong>Tacoma Art Museum</strong></a>, in Chihuly's hometown. Tacoma also houses the permanent Chihuly Bridge of Glass installation linking the museum district to the waterfront.</p>`,
    faqs: [
      { question: "Where can I see this Chihuly piece?", answer: "This Venetian is at the <a href=\"/apps/masterpieces/museum/tacoma-art-museum\"><strong>Tacoma Art Museum</strong></a> in Washington state. Tacoma is Chihuly's hometown and features several permanent installations of his glass art." },
      { question: "What is the Venetians series?", answer: "Chihuly's <strong>Venetians</strong> (begun 1988) reference Murano glass traditions with bold, colorful forms that push beyond functional vessels into pure sculpture. He studied in Murano on a 1968 Fulbright Fellowship." },
      { question: "Does Chihuly blow the glass himself?", answer: "Since injuries in the 1970s, Chihuly has <strong>directed teams of glassblowers</strong> rather than blowing glass himself. He creates watercolor sketches and guides the process, working more like an architect than a solo craftsman." }
    ]
  },
  'portrait-family-kaulbach': {
    description: `<p><strong>Friedrich August von Kaulbach</strong> painted this intimate family portrait in 1907, showing a domestic scene with the warmth and naturalism of the Munich school. The artist's family is arranged in a comfortable interior, dressed in the fashions of early 20th-century bourgeois Germany. <strong>Soft, diffused light</strong> falls across their faces, lending the scene an air of quiet contentment.</p><p>Kaulbach came from a dynasty of German painters: his grandfather Wilhelm was one of the most famous history painters of the 19th century. Friedrich August focused instead on portraits and genre scenes, working in a style that balanced academic skill with a more relaxed, modern sensibility. His portraits were prized by the Munich elite.</p><p>The painting is held at the <a href="/apps/masterpieces/museum/frye-art-museum"><strong>Frye Art Museum</strong></a> in Seattle, which houses one of the finest collections of 19th-century German painting in the United States. The Frye's founders, Charles and Emma Frye, collected heavily from the Munich school.</p>`,
    faqs: [
      { question: "Where can I see this painting?", answer: "It's at the <a href=\"/apps/masterpieces/museum/frye-art-museum\"><strong>Frye Art Museum</strong></a> in Seattle, Washington. The Frye specializes in 19th-century European painting, particularly the Munich school." },
      { question: "Who was Friedrich August von Kaulbach?", answer: "<strong>Kaulbach</strong> (1850-1920) was a German portraitist from a prominent painting family. His grandfather Wilhelm von Kaulbach was one of Germany's most celebrated history painters." },
      { question: "Is admission free at the Frye?", answer: "Yes, the <a href=\"/apps/masterpieces/museum/frye-art-museum\"><strong>Frye Art Museum</strong></a> has always been <strong>free</strong>, per the founders' wishes. It's one of the few free art museums on the West Coast." }
    ]
  },

  // Egyptian pieces
  'tomb-of-nefertari-paintings': {
    description: `<p>The <strong>Tomb of Nefertari</strong> (QV66) in the Valley of the Queens contains what many consider the <strong>finest wall paintings in all of ancient Egypt</strong>. Painted around 1250 BC for the favorite wife of Ramesses II, the walls glow with vivid blues, golds, reds, and whites depicting Nefertari's journey through the afterlife.</p><p>The paintings show Nefertari guided by gods including Isis, Hathor, and Osiris. She's depicted in a pleated white linen gown and golden vulture crown, playing senet (a board game symbolizing the passage to the afterlife), and making offerings. The figures are rendered with unusual grace, their poses more fluid and expressive than typical New Kingdom tomb art.</p><p>The tomb was discovered by Italian archaeologist Ernesto Schiaparelli in 1904. Centuries of salt damage and flooding nearly destroyed the paintings. A major Getty Conservation Institute restoration (1986-1992) stabilized them. Today the tomb is open to limited visitors at the Theban necropolis in <strong>Luxor, Egypt</strong>, with strict limits to protect the fragile surfaces.</p>`,
    faqs: [
      { question: "Can you visit the Tomb of Nefertari?", answer: "Yes, but access is <strong>strictly limited</strong> and requires a special ticket beyond the standard Valley of the Queens pass. Visit times are capped at about 10 minutes to protect the fragile paintings." },
      { question: "Who was Nefertari?", answer: "<strong>Nefertari</strong> was the principal wife of Ramesses II and one of ancient Egypt's most powerful queens. Ramesses called her \"the one for whom the sun shines\" and built her the finest tomb in the Valley of the Queens." },
      { question: "Why are these paintings considered the finest in Egypt?", answer: "The <strong>color, composition, and detail</strong> surpass most Egyptian tomb art. The figures are unusually graceful, the pigments remarkably preserved, and the artistic skill evident in every carefully rendered hieroglyph and divine figure." }
    ]
  },
  'scarab-pectoral-tutankhamun': {
    description: `<p>This <strong>pectoral chest ornament</strong> from the tomb of Tutankhamun features a large scarab beetle carved from Libyan desert glass, flanked by cobras and topped with a lunar barque. The scarab holds the <strong>Eye of Horus</strong> between its front legs while its hind legs rest on a shen ring (symbol of eternity) and lily flowers. Gold, carnelian, lapis lazuli, turquoise, and glass inlays create a riot of color.</p><p>The piece was found in the Treasury of Tutankhamun's tomb by Howard Carter's team in 1922. It's one of dozens of pectoral ornaments placed on and around the young king's mummy, each with layered religious symbolism. The scarab represents Khepri, the sun god at dawn, pushing the sun across the sky each morning.</p><p>The pectoral is displayed at the <a href="/apps/masterpieces/museum/grand-egyptian-museum"><strong>Grand Egyptian Museum</strong></a> near the Giza pyramids. The <strong>Libyan desert glass</strong> at its center, formed by a meteorite impact 26 million years ago, makes this one of the most scientifically interesting objects in the Tutankhamun collection.</p>`,
    faqs: [
      { question: "Where can I see the Scarab Pectoral?", answer: "It's at the <a href=\"/apps/masterpieces/museum/grand-egyptian-museum\"><strong>Grand Egyptian Museum</strong></a> near the Giza pyramids in Cairo, displayed among the thousands of objects from Tutankhamun's tomb." },
      { question: "What is the scarab made from?", answer: "The central scarab is carved from <strong>Libyan desert glass</strong>, a pale yellow-green glass formed by a meteorite impact about 26 million years ago. It's one of the rarest materials used in ancient Egyptian jewelry." },
      { question: "What does the scarab symbolize?", answer: "The scarab represents <strong>Khepri</strong>, the god of the rising sun. Egyptians observed dung beetles rolling balls of earth and associated the action with the sun's daily journey across the sky. Scarabs symbolized rebirth and regeneration." }
    ]
  }
};

async function seed() {
  for (const [slug, data] of Object.entries(enrichments)) {
    try {
      await prisma.artwork.update({
        where: { slug },
        data: { description: data.description, faqs: data.faqs, updatedAt: new Date() }
      });
      console.log(`✓ ${slug}: description + ${data.faqs.length} FAQs`);
    } catch (err) { console.error(`✗ Failed: ${slug} - ${err.message}`); }
  }
  await prisma.$disconnect();
}
seed();
