import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const newArtists = [
  {
    slug: "jan-van-eyck",
    name: "Jan van Eyck",
    birthYear: 1390,
    deathYear: 1441,
    nationality: "Flemish",
    movements: ["Northern Renaissance"],
    bioShort: "Jan van Eyck was a Flemish painter active in Bruges, considered one of the most significant Northern Renaissance artists and a pioneer of oil painting techniques.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Portrait_of_a_Man_by_Jan_van_Eyck-small.jpg/800px-Portrait_of_a_Man_by_Jan_van_Eyck-small.jpg",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Jan_van_Eyck",
  },
  {
    slug: "hieronymus-bosch",
    name: "Hieronymus Bosch",
    birthYear: 1450,
    deathYear: 1516,
    nationality: "Dutch",
    movements: ["Northern Renaissance"],
    bioShort: "Hieronymus Bosch was a Dutch painter known for his fantastical imagery, detailed landscapes, and illustrations of religious concepts and narratives.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Jheronimus_Bosch.jpg/800px-Jheronimus_Bosch.jpg",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Hieronymus_Bosch",
  },
  {
    slug: "titian",
    name: "Titian",
    birthYear: 1488,
    deathYear: 1576,
    nationality: "Italian",
    movements: ["Renaissance"],
    bioShort: "Titian was the most important member of the 16th-century Venetian school, recognized as a master of color and one of the greatest portrait painters.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Tiziano_Vecellio_%28Titian%29_-_Self-Portrait_-_WGA22973.jpg/800px-Tiziano_Vecellio_%28Titian%29_-_Self-Portrait_-_WGA22973.jpg",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Titian",
  },
  {
    slug: "el-greco",
    name: "El Greco",
    birthYear: 1541,
    deathYear: 1614,
    nationality: "Greek-Spanish",
    movements: ["Renaissance", "Baroque"],
    bioShort: "El Greco was a Greek painter, sculptor, and architect who spent most of his life in Spain. His dramatic expressionistic style puzzled contemporaries but was later greatly admired.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/El_Greco_-_Portrait_of_a_Man_-_WGA10554.jpg/800px-El_Greco_-_Portrait_of_a_Man_-_WGA10554.jpg",
    wikipediaUrl: "https://en.wikipedia.org/wiki/El_Greco",
  },
  {
    slug: "francisco-goya",
    name: "Francisco Goya",
    birthYear: 1746,
    deathYear: 1828,
    nationality: "Spanish",
    movements: ["Romanticism"],
    bioShort: "Francisco Goya was a Spanish romantic painter and printmaker, considered the most important Spanish artist of the late 18th and early 19th centuries.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Francisco_de_Goya_y_Lucientes_-_Self-Portrait_-_WGA10061.jpg/800px-Francisco_de_Goya_y_Lucientes_-_Self-Portrait_-_WGA10061.jpg",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Francisco_Goya",
  },
  {
    slug: "gustave-courbet",
    name: "Gustave Courbet",
    birthYear: 1819,
    deathYear: 1877,
    nationality: "French",
    movements: ["Realism"],
    bioShort: "Gustave Courbet was a French painter who led the Realist movement in 19th-century French painting, known for challenging artistic conventions.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Gustave_Courbet_-_Self-Portrait_%28Man_with_Leather_Belt%29_-_WGA05478.jpg/800px-Gustave_Courbet_-_Self-Portrait_%28Man_with_Leather_Belt%29_-_WGA05478.jpg",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Gustave_Courbet",
  },
  {
    slug: "edouard-manet",
    name: "Édouard Manet",
    birthYear: 1832,
    deathYear: 1883,
    nationality: "French",
    movements: ["Impressionism", "Realism"],
    bioShort: "Édouard Manet was a French modernist painter and a pivotal figure in the transition from Realism to Impressionism.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Edouard_Manet_-_Self-Portrait_with_Palette.jpg/800px-Edouard_Manet_-_Self-Portrait_with_Palette.jpg",
    wikipediaUrl: "https://en.wikipedia.org/wiki/%C3%89douard_Manet",
  },
  {
    slug: "camille-pissarro",
    name: "Camille Pissarro",
    birthYear: 1830,
    deathYear: 1903,
    nationality: "French",
    movements: ["Impressionism", "Post-Impressionism"],
    bioShort: "Camille Pissarro was a Danish-French Impressionist and Neo-Impressionist painter. He was a mentor to many famous artists including Cézanne and Gauguin.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Camille_Pissarro_-_Portrait_de_l%27artiste_-_PPP3104_-_Mus%C3%A9e_des_Beaux-Arts_de_la_ville_de_Paris.jpg/800px-Camille_Pissarro_-_Portrait_de_l%27artiste_-_PPP3104_-_Mus%C3%A9e_des_Beaux-Arts_de_la_ville_de_Paris.jpg",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Camille_Pissarro",
  },
  {
    slug: "paul-cezanne",
    name: "Paul Cézanne",
    birthYear: 1839,
    deathYear: 1906,
    nationality: "French",
    movements: ["Post-Impressionism"],
    bioShort: "Paul Cézanne was a French artist and Post-Impressionist painter whose work laid the foundations of the transition from 19th-century art to Cubism.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Paul_C%C3%A9zanne%2C_photographed_by_Nadar%2C_c1861.jpg/800px-Paul_C%C3%A9zanne%2C_photographed_by_Nadar%2C_c1861.jpg",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Paul_C%C3%A9zanne",
  },
  {
    slug: "paul-gauguin",
    name: "Paul Gauguin",
    birthYear: 1848,
    deathYear: 1903,
    nationality: "French",
    movements: ["Post-Impressionism"],
    bioShort: "Paul Gauguin was a French Post-Impressionist artist known for his bold use of color and synthetist style, particularly in his Tahitian paintings.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Paul_Gauguin_1891.png/800px-Paul_Gauguin_1891.png",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Paul_Gauguin",
  },
  {
    slug: "henri-toulouse-lautrec",
    name: "Henri de Toulouse-Lautrec",
    birthYear: 1864,
    deathYear: 1901,
    nationality: "French",
    movements: ["Post-Impressionism"],
    bioShort: "Henri de Toulouse-Lautrec was a French painter, printmaker, and illustrator, known for his colorful portrayals of the theatrical and bohemian life of Paris.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Henri_de_Toulouse-Lautrec_-_Autoportrait_-_Google_Art_Project.jpg/800px-Henri_de_Toulouse-Lautrec_-_Autoportrait_-_Google_Art_Project.jpg",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Henri_de_Toulouse-Lautrec",
  },
  {
    slug: "georges-seurat",
    name: "Georges Seurat",
    birthYear: 1859,
    deathYear: 1891,
    nationality: "French",
    movements: ["Post-Impressionism"],
    bioShort: "Georges Seurat was a French post-Impressionist painter and draftsman. He devised the painting technique known as pointillism.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Georges_Seurat_1888.jpg/800px-Georges_Seurat_1888.jpg",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Georges_Seurat",
  },
  {
    slug: "henri-matisse",
    name: "Henri Matisse",
    birthYear: 1869,
    deathYear: 1954,
    nationality: "French",
    movements: ["Fauvism", "Expressionism"],
    bioShort: "Henri Matisse was a French visual artist, known for his use of color and his fluid and original draughtsmanship. He was a leading figure in Fauvism.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/HenriMatisse.JPG/800px-HenriMatisse.JPG",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Henri_Matisse",
  },
  {
    slug: "amedeo-modigliani",
    name: "Amedeo Modigliani",
    birthYear: 1884,
    deathYear: 1920,
    nationality: "Italian",
    movements: ["Expressionism"],
    bioShort: "Amedeo Modigliani was an Italian painter and sculptor known for portraits and nudes in a modern style characterized by elongated faces and figures.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Amedeo_Modigliani_Photo.jpg/800px-Amedeo_Modigliani_Photo.jpg",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Amedeo_Modigliani",
  },
  {
    slug: "egon-schiele",
    name: "Egon Schiele",
    birthYear: 1890,
    deathYear: 1918,
    nationality: "Austrian",
    movements: ["Expressionism"],
    bioShort: "Egon Schiele was an Austrian Expressionist painter. His work is noted for its raw sexuality and intensity, and for the twisted body shapes he employed.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Egon_Schiele_-_Self-Portrait_with_Physalis_-_Google_Art_Project.jpg/800px-Egon_Schiele_-_Self-Portrait_with_Physalis_-_Google_Art_Project.jpg",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Egon_Schiele",
  },
  {
    slug: "gustav-klimt",
    name: "Gustav Klimt",
    birthYear: 1862,
    deathYear: 1918,
    nationality: "Austrian",
    movements: ["Expressionism"],
    bioShort: "Gustav Klimt was an Austrian symbolist painter and one of the most prominent members of the Vienna Secession movement, known for his gold leaf paintings.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Klimt.jpg/800px-Klimt.jpg",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Gustav_Klimt",
  },
  {
    slug: "georges-braque",
    name: "Georges Braque",
    birthYear: 1882,
    deathYear: 1963,
    nationality: "French",
    movements: ["Cubism", "Fauvism"],
    bioShort: "Georges Braque was a major 20th-century French painter, collagist, and sculptor. Along with Pablo Picasso, he developed Cubism.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Georges_Braque%2C_1908%2C_photograph_published_in_Gelett_Burgess%2C_The_Wild_Men_of_Paris%2C_The_Architectural_Record%2C_May_1910.jpg/800px-Georges_Braque%2C_1908%2C_photograph_published_in_Gelett_Burgess%2C_The_Wild_Men_of_Paris%2C_The_Architectural_Record%2C_May_1910.jpg",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Georges_Braque",
  },
  {
    slug: "jackson-pollock",
    name: "Jackson Pollock",
    birthYear: 1912,
    deathYear: 1956,
    nationality: "American",
    movements: ["Abstract Expressionism"],
    bioShort: "Jackson Pollock was an American painter and a major figure in the abstract expressionist movement. He was known for his drip technique.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Pollock1949.jpg/800px-Pollock1949.jpg",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Jackson_Pollock",
  },
  {
    slug: "mark-rothko",
    name: "Mark Rothko",
    birthYear: 1903,
    deathYear: 1970,
    nationality: "American",
    movements: ["Abstract Expressionism"],
    bioShort: "Mark Rothko was an American painter of Lithuanian descent, best known for his color field paintings featuring large rectangular blocks of color.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/1/1e/Mark_Rothko_1959.jpg",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Mark_Rothko",
  },
  {
    slug: "willem-de-kooning",
    name: "Willem de Kooning",
    birthYear: 1904,
    deathYear: 1997,
    nationality: "Dutch-American",
    movements: ["Abstract Expressionism"],
    bioShort: "Willem de Kooning was a Dutch-American abstract expressionist artist, known for his gestural style and his series of Women paintings.",
    imageUrl: null, // Copyrighted
    wikipediaUrl: "https://en.wikipedia.org/wiki/Willem_de_Kooning",
  },
  {
    slug: "jean-michel-basquiat",
    name: "Jean-Michel Basquiat",
    birthYear: 1960,
    deathYear: 1988,
    nationality: "American",
    movements: ["Neo-Expressionism"],
    bioShort: "Jean-Michel Basquiat was an American artist of Haitian and Puerto Rican descent. His art focused on dichotomies such as wealth versus poverty.",
    imageUrl: null, // Copyrighted
    wikipediaUrl: "https://en.wikipedia.org/wiki/Jean-Michel_Basquiat",
  },
];

const newArtworks = [
  // Jan van Eyck
  {
    slug: "arnolfini-portrait",
    title: "The Arnolfini Portrait",
    year: 1434,
    medium: "Oil on oak panel",
    dimensions: "82.2 cm × 60 cm",
    description: "A double portrait of Italian merchant Giovanni di Nicolao Arnolfini and his wife, believed to be a record of their marriage or betrothal.",
    historicalSignificance: "One of the most original and complex paintings in Western art history, famous for its use of perspective and symbolism.",
    galleryRoom: "Room 56",
    isPermanent: true,
    searchVolumeTier: 1,
    artistSlug: "jan-van-eyck",
    museumSlug: "national-gallery",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Van_Eyck_-_Arnolfini_Portrait.jpg/800px-Van_Eyck_-_Arnolfini_Portrait.jpg",
  },
  // Hieronymus Bosch
  {
    slug: "garden-of-earthly-delights",
    title: "The Garden of Earthly Delights",
    year: 1505,
    medium: "Oil on oak panels",
    dimensions: "220 cm × 389 cm",
    description: "A triptych depicting the Garden of Eden, a fantastical paradise, and a hellscape. It remains one of art's most enigmatic works.",
    historicalSignificance: "One of the most famous works of the Northern Renaissance, its complex imagery has inspired countless interpretations.",
    galleryRoom: "Room 56A",
    isPermanent: true,
    searchVolumeTier: 1,
    artistSlug: "hieronymus-bosch",
    museumSlug: "prado",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/The_Garden_of_earthly_delights.jpg/1280px-The_Garden_of_earthly_delights.jpg",
  },
  // Titian
  {
    slug: "venus-of-urbino",
    title: "Venus of Urbino",
    year: 1538,
    medium: "Oil on canvas",
    dimensions: "119 cm × 165 cm",
    description: "A reclining female nude, traditionally identified as Venus, goddess of love, in a contemporary Venetian setting.",
    historicalSignificance: "One of the most influential paintings of the female nude in Western art, later influencing Manet's Olympia.",
    galleryRoom: "Room 28",
    isPermanent: true,
    searchVolumeTier: 2,
    artistSlug: "titian",
    museumSlug: "uffizi",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Tiziano_-_Venere_di_Urbino_-_Google_Art_Project.jpg/1280px-Tiziano_-_Venere_di_Urbino_-_Google_Art_Project.jpg",
  },
  // El Greco
  {
    slug: "view-of-toledo",
    title: "View of Toledo",
    year: 1600,
    medium: "Oil on canvas",
    dimensions: "121.3 cm × 108.6 cm",
    description: "A dramatic landscape showing the city of Toledo, Spain under a stormy sky, one of the first pure landscape paintings in Western art.",
    historicalSignificance: "One of only two surviving landscapes by El Greco, it foreshadows Expressionism by three centuries.",
    galleryRoom: "Gallery 958",
    isPermanent: true,
    searchVolumeTier: 2,
    artistSlug: "el-greco",
    museumSlug: "met",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/El_Greco_View_of_Toledo.jpg/800px-El_Greco_View_of_Toledo.jpg",
  },
  // Francisco Goya
  {
    slug: "third-of-may-1808",
    title: "The Third of May 1808",
    year: 1814,
    medium: "Oil on canvas",
    dimensions: "268 cm × 347 cm",
    description: "Depicts the execution of Spanish civilians by Napoleon's army during the Peninsular War.",
    historicalSignificance: "A groundbreaking work that broke with traditional war painting, showing the horror of war from the victims' perspective.",
    galleryRoom: "Room 64",
    isPermanent: true,
    searchVolumeTier: 1,
    artistSlug: "francisco-goya",
    museumSlug: "prado",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/El_Tres_de_Mayo%2C_by_Francisco_de_Goya%2C_from_Prado_thin_black_margin.jpg/1280px-El_Tres_de_Mayo%2C_by_Francisco_de_Goya%2C_from_Prado_thin_black_margin.jpg",
  },
  {
    slug: "saturn-devouring-his-son",
    title: "Saturn Devouring His Son",
    year: 1823,
    medium: "Oil mural transferred to canvas",
    dimensions: "143.5 cm × 81.4 cm",
    description: "One of Goya's Black Paintings, depicting the Greek myth of the Titan Cronus eating one of his children.",
    historicalSignificance: "A disturbing masterpiece from Goya's late period, representing the artist's darkest psychological state.",
    galleryRoom: "Room 67",
    isPermanent: true,
    searchVolumeTier: 2,
    artistSlug: "francisco-goya",
    museumSlug: "prado",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg/800px-Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg",
  },
  // Édouard Manet
  {
    slug: "olympia",
    title: "Olympia",
    year: 1863,
    medium: "Oil on canvas",
    dimensions: "130.5 cm × 190 cm",
    description: "A reclining nude woman being attended by a servant who presents flowers from an admirer. The model's confrontational gaze shocked viewers.",
    historicalSignificance: "Caused a scandal when exhibited in 1865, but is now considered a pivotal work that bridged Realism and Impressionism.",
    galleryRoom: "Room 14",
    isPermanent: true,
    searchVolumeTier: 2,
    artistSlug: "edouard-manet",
    museumSlug: "orsay",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Edouard_Manet_-_Olympia_-_Google_Art_Project_3.jpg/1280px-Edouard_Manet_-_Olympia_-_Google_Art_Project_3.jpg",
  },
  {
    slug: "le-dejeuner-sur-lherbe",
    title: "Le Déjeuner sur l'herbe",
    year: 1863,
    medium: "Oil on canvas",
    dimensions: "208 cm × 264.5 cm",
    description: "A nude woman casually lunching with two fully dressed men, a bold departure from academic painting conventions.",
    historicalSignificance: "Rejected by the Paris Salon, it became a rallying point for young artists and a catalyst for Impressionism.",
    galleryRoom: "Room 29",
    isPermanent: true,
    searchVolumeTier: 2,
    artistSlug: "edouard-manet",
    museumSlug: "orsay",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/%C3%89douard_Manet_-_Le_D%C3%A9jeuner_sur_l%27herbe.jpg/1280px-%C3%89douard_Manet_-_Le_D%C3%A9jeuner_sur_l%27herbe.jpg",
  },
  // Paul Cézanne
  {
    slug: "mont-sainte-victoire",
    title: "Mont Sainte-Victoire",
    year: 1887,
    medium: "Oil on canvas",
    dimensions: "67 cm × 92 cm",
    description: "One of many paintings Cézanne made of Mont Sainte-Victoire near his home in Aix-en-Provence.",
    historicalSignificance: "Cézanne's treatment of this subject anticipated Cubism with its geometric simplification of natural forms.",
    galleryRoom: "European Paintings",
    isPermanent: true,
    searchVolumeTier: 2,
    artistSlug: "paul-cezanne",
    museumSlug: "art-institute-chicago",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Paul_C%C3%A9zanne_-_Mont_Sainte-Victoire_-_Google_Art_Project.jpg/1280px-Paul_C%C3%A9zanne_-_Mont_Sainte-Victoire_-_Google_Art_Project.jpg",
  },
  {
    slug: "the-card-players",
    title: "The Card Players",
    year: 1895,
    medium: "Oil on canvas",
    dimensions: "47.5 cm × 57 cm",
    description: "One of five paintings in a series showing Provençal peasants playing cards, known for its monumentality and geometric composition.",
    historicalSignificance: "One version of this series sold for over $250 million, making it one of the most expensive paintings ever sold.",
    galleryRoom: "Room 1",
    isPermanent: true,
    searchVolumeTier: 2,
    artistSlug: "paul-cezanne",
    museumSlug: "orsay",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Les_Joueurs_de_cartes%2C_par_Paul_C%C3%A9zanne.jpg/1280px-Les_Joueurs_de_cartes%2C_par_Paul_C%C3%A9zanne.jpg",
  },
  // Paul Gauguin
  {
    slug: "where-do-we-come-from",
    title: "Where Do We Come From? What Are We? Where Are We Going?",
    year: 1897,
    medium: "Oil on canvas",
    dimensions: "139.1 cm × 374.6 cm",
    description: "Gauguin's largest painting, meant to be read from right to left as an allegory of the human life cycle.",
    historicalSignificance: "Considered Gauguin's masterpiece and testament, painted in Tahiti during a period of suicidal despair.",
    galleryRoom: "Gallery 227",
    isPermanent: true,
    searchVolumeTier: 2,
    artistSlug: "paul-gauguin",
    museumSlug: "mfa-boston",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Paul_Gauguin_-_D%27ou_venons-nous.jpg/1280px-Paul_Gauguin_-_D%27ou_venons-nous.jpg",
  },
  // Georges Seurat
  {
    slug: "sunday-afternoon-on-la-grande-jatte",
    title: "A Sunday Afternoon on the Island of La Grande Jatte",
    year: 1886,
    medium: "Oil on canvas",
    dimensions: "207.6 cm × 308 cm",
    description: "Parisians relaxing in a park on an island in the Seine, painted using tiny dots of color (pointillism).",
    historicalSignificance: "The most famous example of pointillism and one of the most iconic works of the 19th century.",
    galleryRoom: "Gallery 240",
    isPermanent: true,
    searchVolumeTier: 1,
    artistSlug: "georges-seurat",
    museumSlug: "art-institute-chicago",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg/1280px-A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg",
  },
  // Henri Matisse
  {
    slug: "dance-1910",
    title: "Dance",
    year: 1910,
    medium: "Oil on canvas",
    dimensions: "260 cm × 391 cm",
    description: "Five nude figures holding hands and dancing in a circle against a simplified landscape background.",
    historicalSignificance: "A key work of early modern art, demonstrating Matisse's use of bold color and simplified forms.",
    galleryRoom: "Room 345",
    isPermanent: true,
    searchVolumeTier: 2,
    artistSlug: "henri-matisse",
    museumSlug: "hermitage",
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Matissedance.jpg/1280px-Matissedance.jpg",
  },
  // Gustav Klimt
  {
    slug: "the-kiss-klimt",
    title: "The Kiss",
    year: 1908,
    medium: "Oil and gold leaf on canvas",
    dimensions: "180 cm × 180 cm",
    description: "A couple embracing against a golden background, the man bending to kiss the woman on the cheek.",
    historicalSignificance: "Klimt's most famous work and a symbol of Vienna Secession, celebrated for its gold leaf decoration.",
    galleryRoom: "Upper Belvedere",
    isPermanent: true,
    searchVolumeTier: 1,
    artistSlug: "gustav-klimt",
    museumSlug: "belvedere",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg/800px-The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg",
  },
  {
    slug: "portrait-of-adele-bloch-bauer-i",
    title: "Portrait of Adele Bloch-Bauer I",
    year: 1907,
    medium: "Oil and gold on canvas",
    dimensions: "138 cm × 138 cm",
    description: "Also known as The Lady in Gold, a portrait of a Viennese socialite rendered in Klimt's golden style.",
    historicalSignificance: "Sold for $135 million in 2006, making it one of the most expensive paintings ever sold at that time.",
    galleryRoom: "Gallery 20",
    isPermanent: true,
    searchVolumeTier: 2,
    artistSlug: "gustav-klimt",
    museumSlug: "neue-galerie",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Gustav_Klimt%2C_1907%2C_Adele_Bloch-Bauer_I%2C_Neue_Galerie_New_York.jpg/800px-Gustav_Klimt%2C_1907%2C_Adele_Bloch-Bauer_I%2C_Neue_Galerie_New_York.jpg",
  },
  // Jackson Pollock
  {
    slug: "number-1a-1948",
    title: "Number 1A, 1948",
    year: 1948,
    medium: "Oil and enamel paint on canvas",
    dimensions: "172.7 cm × 264.2 cm",
    description: "A large drip painting created by flinging and dripping paint onto a canvas laid on the floor.",
    historicalSignificance: "One of Pollock's most celebrated works, exemplifying his revolutionary drip technique.",
    galleryRoom: "Gallery 19A",
    isPermanent: true,
    searchVolumeTier: 2,
    artistSlug: "jackson-pollock",
    museumSlug: "moma",
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/1/17/Number_1A%2C_1948.png/1280px-Number_1A%2C_1948.png",
  },
  // More Van Gogh
  {
    slug: "irises",
    title: "Irises",
    year: 1889,
    medium: "Oil on canvas",
    dimensions: "71 cm × 93 cm",
    description: "One of several paintings of irises Van Gogh created at the asylum in Saint-Rémy-de-Provence.",
    historicalSignificance: "Van Gogh considered this a 'lightning conductor for my illness,' painted to maintain his sanity.",
    galleryRoom: "The Getty Center",
    isPermanent: true,
    searchVolumeTier: 1,
    artistSlug: "van-gogh",
    museumSlug: "getty",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Irises-Vincent_van_Gogh.jpg/1280px-Irises-Vincent_van_Gogh.jpg",
  },
  {
    slug: "almond-blossoms",
    title: "Almond Blossoms",
    year: 1890,
    medium: "Oil on canvas",
    dimensions: "73.3 cm × 92.4 cm",
    description: "Large blossoming branches against a blue sky, painted to celebrate the birth of his nephew and namesake.",
    historicalSignificance: "Shows Van Gogh's interest in Japanese art and represents hope and new beginnings.",
    galleryRoom: "Van Gogh Museum",
    isPermanent: true,
    searchVolumeTier: 1,
    artistSlug: "van-gogh",
    museumSlug: "van-gogh-museum",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Vincent_van_Gogh_-_Almond_blossom_-_Google_Art_Project.jpg/1280px-Vincent_van_Gogh_-_Almond_blossom_-_Google_Art_Project.jpg",
  },
  {
    slug: "self-portrait-1889",
    title: "Self-Portrait",
    year: 1889,
    medium: "Oil on canvas",
    dimensions: "65 cm × 54 cm",
    description: "One of Van Gogh's many self-portraits, painted at Saint-Rémy, showing swirling blue and green backgrounds.",
    historicalSignificance: "One of Van Gogh's most famous self-portraits, revealing his psychological state through color and brushwork.",
    galleryRoom: "Room 29",
    isPermanent: true,
    searchVolumeTier: 2,
    artistSlug: "van-gogh",
    museumSlug: "orsay",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project.jpg/800px-Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project.jpg",
  },
  // More Monet
  {
    slug: "impression-sunrise",
    title: "Impression, Sunrise",
    year: 1872,
    medium: "Oil on canvas",
    dimensions: "48 cm × 63 cm",
    description: "A view of the port of Le Havre at sunrise, with boats and industrial smokestacks through morning mist.",
    historicalSignificance: "The painting that gave Impressionism its name after a critic used the term mockingly.",
    galleryRoom: "Marmottan Monet Museum",
    isPermanent: true,
    searchVolumeTier: 1,
    artistSlug: "claude-monet",
    museumSlug: "marmottan",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Monet_-_Impression%2C_Sunrise.jpg/1280px-Monet_-_Impression%2C_Sunrise.jpg",
  },
  {
    slug: "haystacks-end-of-summer",
    title: "Haystacks (End of Summer)",
    year: 1891,
    medium: "Oil on canvas",
    dimensions: "60 cm × 100 cm",
    description: "Part of Monet's series of 25 paintings showing haystacks near his home in Giverny at different times of day.",
    historicalSignificance: "One of Monet's most celebrated series, demonstrating his obsession with light and atmosphere.",
    galleryRoom: "Gallery 243",
    isPermanent: true,
    searchVolumeTier: 2,
    artistSlug: "claude-monet",
    museumSlug: "art-institute-chicago",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Claude_Monet_-_Stacks_of_Wheat_%28End_of_Summer%29_-_1985.1103_-_Art_Institute_of_Chicago.jpg/1280px-Claude_Monet_-_Stacks_of_Wheat_%28End_of_Summer%29_-_1985.1103_-_Art_Institute_of_Chicago.jpg",
  },
  // More Rembrandt
  {
    slug: "self-portrait-rembrandt-1659",
    title: "Self-Portrait",
    year: 1659,
    medium: "Oil on canvas",
    dimensions: "84.5 cm × 66 cm",
    description: "One of Rembrandt's most intimate self-portraits, painted at age 53 during a period of financial difficulty.",
    historicalSignificance: "Considered one of the greatest self-portraits ever painted, revealing profound psychological depth.",
    galleryRoom: "Gallery 964",
    isPermanent: true,
    searchVolumeTier: 2,
    artistSlug: "rembrandt",
    museumSlug: "met",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Rembrandt_van_Rijn_-_Self-Portrait_-_Google_Art_Project.jpg/800px-Rembrandt_van_Rijn_-_Self-Portrait_-_Google_Art_Project.jpg",
  },
  {
    slug: "the-anatomy-lesson-of-dr-nicolaes-tulp",
    title: "The Anatomy Lesson of Dr. Nicolaes Tulp",
    year: 1632,
    medium: "Oil on canvas",
    dimensions: "169.5 cm × 216.5 cm",
    description: "A group portrait of surgeons observing an anatomy lesson, showcasing Rembrandt's mastery of light and composition.",
    historicalSignificance: "The painting that established Rembrandt's reputation as a master portraitist at age 26.",
    galleryRoom: "Mauritshuis Gallery",
    isPermanent: true,
    searchVolumeTier: 2,
    artistSlug: "rembrandt",
    museumSlug: "mauritshuis",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Rembrandt_-_The_Anatomy_Lesson_of_Dr_Nicolaes_Tulp.jpg/1280px-Rembrandt_-_The_Anatomy_Lesson_of_Dr_Nicolaes_Tulp.jpg",
  },
  // More Vermeer
  {
    slug: "the-milkmaid",
    title: "The Milkmaid",
    year: 1660,
    medium: "Oil on canvas",
    dimensions: "45.5 cm × 41 cm",
    description: "A kitchen maid pouring milk, one of Vermeer's most beloved works celebrating quiet domestic labor.",
    historicalSignificance: "Renowned for its stunning handling of light and the dignity it bestows on everyday work.",
    galleryRoom: "Gallery of Honour",
    isPermanent: true,
    searchVolumeTier: 1,
    artistSlug: "johannes-vermeer",
    museumSlug: "rijksmuseum",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.jpg/800px-Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.jpg",
  },
  // More Renoir
  {
    slug: "dance-at-le-moulin-de-la-galette",
    title: "Dance at Le Moulin de la Galette",
    year: 1876,
    medium: "Oil on canvas",
    dimensions: "131 cm × 175 cm",
    description: "Working-class Parisians enjoying a Sunday afternoon at an outdoor dance garden in Montmartre.",
    historicalSignificance: "One of Impressionism's most celebrated works, capturing the joie de vivre of Parisian life.",
    galleryRoom: "Room 32",
    isPermanent: true,
    searchVolumeTier: 1,
    artistSlug: "pierre-auguste-renoir",
    museumSlug: "orsay",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Auguste_Renoir_-_Dance_at_Le_Moulin_de_la_Galette_-_Mus%C3%A9e_d%27Orsay_RF_2739_%28derivative_work_-_AutoContrast_edit_in_LCH_space%29.jpg/1280px-Auguste_Renoir_-_Dance_at_Le_Moulin_de_la_Galette_-_Mus%C3%A9e_d%27Orsay_RF_2739_%28derivative_work_-_AutoContrast_edit_in_LCH_space%29.jpg",
  },
  // More Degas
  {
    slug: "the-dance-class",
    title: "The Dance Class",
    year: 1874,
    medium: "Oil on canvas",
    dimensions: "83.5 cm × 77.2 cm",
    description: "Ballet dancers in a rehearsal room with their instructor, showing Degas's fascination with movement and light.",
    historicalSignificance: "One of Degas's most famous ballet paintings, showcasing his innovative cropping and viewpoint.",
    galleryRoom: "Gallery 815",
    isPermanent: true,
    searchVolumeTier: 2,
    artistSlug: "edgar-degas",
    museumSlug: "met",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Edgar_Degas_-_The_Dance_Class_-_Google_Art_Project.jpg/800px-Edgar_Degas_-_The_Dance_Class_-_Google_Art_Project.jpg",
  },
];

const newMuseums = [
  {
    slug: "belvedere",
    name: "Belvedere Museum",
    city: "Vienna",
    country: "Austria",
    address: "Prinz Eugen-Straße 27, 1030 Vienna",
    websiteUrl: "https://www.belvedere.at",
    ticketUrl: "https://www.belvedere.at/en/tickets",
    ticketPriceRange: "€16.90",
    description: "The Belvedere houses the world's largest collection of Gustav Klimt paintings, including The Kiss, as well as masterpieces by Schiele and Kokoschka.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Wien_-_Schloss_Belvedere%2C_oberes_%285%29.JPG/1280px-Wien_-_Schloss_Belvedere%2C_oberes_%285%29.JPG",
  },
  {
    slug: "neue-galerie",
    name: "Neue Galerie",
    city: "New York",
    country: "USA",
    address: "1048 Fifth Avenue, New York, NY 10028",
    websiteUrl: "https://www.neuegalerie.org",
    ticketUrl: "https://www.neuegalerie.org/visit",
    ticketPriceRange: "$25",
    description: "The Neue Galerie is dedicated to German and Austrian art of the early 20th century, including Klimt's Portrait of Adele Bloch-Bauer I.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Neue_Galerie_NYC_002.JPG/800px-Neue_Galerie_NYC_002.JPG",
  },
  {
    slug: "mfa-boston",
    name: "Museum of Fine Arts, Boston",
    city: "Boston",
    country: "USA",
    address: "465 Huntington Avenue, Boston, MA 02115",
    websiteUrl: "https://www.mfa.org",
    ticketUrl: "https://www.mfa.org/tickets",
    ticketPriceRange: "$27",
    description: "One of the largest art museums in the United States, with collections spanning ancient Egyptian art to contemporary works.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Museum_of_Fine_Arts%2C_Boston.jpg/1280px-Museum_of_Fine_Arts%2C_Boston.jpg",
  },
  {
    slug: "getty",
    name: "J. Paul Getty Museum",
    city: "Los Angeles",
    country: "USA",
    address: "1200 Getty Center Drive, Los Angeles, CA 90049",
    websiteUrl: "https://www.getty.edu",
    ticketUrl: "https://www.getty.edu/visit/",
    ticketPriceRange: "Free (parking $20)",
    description: "Houses European paintings, drawings, sculpture, and decorative arts from the Middle Ages to the present, including Van Gogh's Irises.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/J._Paul_Getty_Museum_2.jpg/1280px-J._Paul_Getty_Museum_2.jpg",
  },
  {
    slug: "marmottan",
    name: "Musée Marmottan Monet",
    city: "Paris",
    country: "France",
    address: "2 Rue Louis Boilly, 75016 Paris",
    websiteUrl: "https://www.marmottan.fr",
    ticketUrl: "https://www.marmottan.fr/en/practical-information/",
    ticketPriceRange: "€14",
    description: "Houses the world's largest collection of Monet's works, including Impression, Sunrise, which gave Impressionism its name.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Mus%C3%A9e_Marmottan_Monet%2C_Paris_001.JPG/800px-Mus%C3%A9e_Marmottan_Monet%2C_Paris_001.JPG",
  },
  {
    slug: "mauritshuis",
    name: "Mauritshuis",
    city: "The Hague",
    country: "Netherlands",
    address: "Plein 29, 2511 CS The Hague",
    websiteUrl: "https://www.mauritshuis.nl",
    ticketUrl: "https://www.mauritshuis.nl/en/visit/",
    ticketPriceRange: "€17.50",
    description: "Home to Vermeer's Girl with a Pearl Earring and Rembrandt's The Anatomy Lesson, the Mauritshuis is a jewel of Dutch Golden Age art.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Mauritshuis_Den_Haag.jpg/1280px-Mauritshuis_Den_Haag.jpg",
  },
];

async function main() {
  console.log("Starting to add new art and artists...");

  // Add new museums first
  for (const museum of newMuseums) {
    const existing = await prisma.museum.findUnique({ where: { slug: museum.slug } });
    if (!existing) {
      await prisma.museum.create({ data: museum });
      console.log(`Created museum: ${museum.name}`);
    } else {
      console.log(`Museum already exists: ${museum.name}`);
    }
  }

  // Add new artists
  for (const artist of newArtists) {
    const existing = await prisma.artist.findUnique({ where: { slug: artist.slug } });
    if (!existing) {
      const { movements, ...artistData } = artist;

      // Find movement IDs
      const movementRecords = await prisma.movement.findMany({
        where: { name: { in: movements } },
      });

      await prisma.artist.create({
        data: {
          ...artistData,
          movements: {
            connect: movementRecords.map((m) => ({ id: m.id })),
          },
        },
      });
      console.log(`Created artist: ${artist.name}`);
    } else {
      console.log(`Artist already exists: ${artist.name}`);
    }
  }

  // Add new artworks
  for (const artwork of newArtworks) {
    const existing = await prisma.artwork.findUnique({ where: { slug: artwork.slug } });
    if (!existing) {
      const { artistSlug, museumSlug, ...artworkData } = artwork;

      const artist = await prisma.artist.findUnique({ where: { slug: artistSlug } });
      const museum = await prisma.museum.findUnique({ where: { slug: museumSlug } });

      if (artist && museum) {
        await prisma.artwork.create({
          data: {
            ...artworkData,
            artistId: artist.id,
            museumId: museum.id,
          },
        });
        console.log(`Created artwork: ${artwork.title}`);
      } else {
        console.log(`Skipping ${artwork.title} - artist or museum not found`);
      }
    } else {
      console.log(`Artwork already exists: ${artwork.title}`);
    }
  }

  console.log("\nDone! Added new art and artists.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
