import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Expanded FAQs for 25 artists - 35-60 words per answer, 3-4 interlinks spread across all FAQs
const artistFAQs: Record<string, { question: string; answer: string }[]> = {
  "carolus-duran": [
    { question: "What art movement was Carolus-Duran associated with?", answer: `Carolus-Duran worked within <a href="/apps/masterpieces/movement/realism"><strong>Realism</strong></a> before developing his signature portrait style influenced by Velázquez. After traveling to Spain in the 1860s, he abandoned Courbet's dark realism for the Spanish master's fluid brushwork and direct painting technique, which made him one of Paris's most sought-after portraitists.` },
    { question: "Who were Carolus-Duran's famous students?", answer: `His most famous pupil was <a href="/apps/masterpieces/artist/john-singer-sargent"><strong>John Singer Sargent</strong></a>, who studied with him from 1874 and painted a celebrated portrait of his teacher in 1879. Other notable students included Carroll Beckwith, William Low, and Theodore Robinson. His teaching method emphasized painting directly from the model without preliminary drawing.` },
    { question: "Where can I see Carolus-Duran's paintings?", answer: `His work hangs at the <a href="/apps/masterpieces/museum/musee-dorsay"><strong>Musée d'Orsay</strong></a> in Paris, the Palais des Beaux-Arts de Lille (his hometown), and the Fine Arts Museums of San Francisco, which holds his tender portrait of his daughter Marie-Anne from 1874.` },
    { question: "What was Carolus-Duran's painting technique?", answer: `He championed the alla prima method, painting directly on canvas with loaded brushes rather than building up layers over careful drawings. This approach, derived from Velázquez and later Frans Hals, emphasized tonal relationships and immediate observation. He passed this technique to Sargent, who refined it into his own brilliant style.` },
    { question: "What honors did Carolus-Duran receive?", answer: `He co-founded the Société Nationale des Beaux-Arts with Ernest Meissonier and Pierre Puvis de Chavannes, becoming its president in 1898. In 1905, he was appointed director of the French Academy in Rome, the most prestigious post for a French artist, which he held until 1913.` }
  ],

  "frida-kahlo": [
    { question: "What art movement was Frida Kahlo part of?", answer: `André Breton declared Kahlo a <a href="/apps/masterpieces/movement/surrealism"><strong>Surrealist</strong></a> in 1938, though she famously rejected the label: "I never painted dreams. I painted my own reality." Her deeply personal <a href="https://luxurywallart.com/collections/portrait-art" target="_blank" rel="noopener"><strong>self-portraits</strong></a> blend Mexican folk traditions, Catholic iconography, and unflinching depictions of physical and emotional suffering.` },
    { question: "Where can I see Frida Kahlo's paintings?", answer: `The <strong>Frida Kahlo Museum</strong> (Casa Azul) in Coyoacán, Mexico City occupies her childhood home and displays personal belongings alongside artworks. The <a href="/apps/masterpieces/museum/moma"><strong>Museum of Modern Art</strong></a> in New York, the SFMOMA, and Mexico City's Museo Dolores Olmedo hold major works.` },
    { question: "What subjects did Frida Kahlo paint?", answer: `Of her 200 paintings, 55 are self-portraits exploring identity, physical suffering, and emotional turmoil. Her 1925 bus accident left her with lifelong injuries that became central subjects. She painted her miscarriages, surgeries, and troubled marriage to muralist Diego Rivera with brutal honesty and <a href="https://luxurywallart.com/collections/colorful-artwork" target="_blank" rel="noopener"><strong>vivid color</strong></a>.` },
    { question: "How did Frida Kahlo start painting?", answer: `The devastating 1925 bus accident that broke her spine, collarbone, ribs, and pelvis left her bedridden for months. Her parents installed a mirror above her bed and provided painting supplies. She taught herself while recovering, producing her first self-portrait in 1926. The accident shaped both her art and chronic pain.` },
    { question: "What is Frida Kahlo's auction record?", answer: `Her 1949 painting <em>Diego y yo</em> sold for $34.9 million at Sotheby's in 2021, then the record for a Latin American artist. In 2022, her self-portrait <em>Diego y yo</em> sold again for $54.7 million, making her the most valuable female Latin American artist at auction.` }
  ],

  "michelangelo": [
    { question: "What art movement was Michelangelo part of?", answer: `Michelangelo was a defining figure of the <a href="/apps/masterpieces/movement/renaissance"><strong>High Renaissance</strong></a>, working alongside Leonardo da Vinci and Raphael. His powerful, muscular figures and emotional intensity later influenced <a href="/apps/masterpieces/movement/mannerism"><strong>Mannerism</strong></a>. He considered himself primarily a sculptor, though his painted ceiling changed art history.` },
    { question: "Where can I see Michelangelo's works?", answer: `The Sistine Chapel ceiling and <em>The Last Judgment</em> are in the <a href="/apps/masterpieces/museum/vatican-museums"><strong>Vatican Museums</strong></a>. His <em>David</em> stands in Florence's Galleria dell'Accademia. The <em>Pietà</em> is in St. Peter's Basilica. The <a href="/apps/masterpieces/museum/uffizi"><strong>Uffizi</strong></a> holds his only surviving panel painting.` },
    { question: "How long did Michelangelo work on the Sistine Chapel?", answer: `He painted the ceiling from 1508 to 1512, four years of grueling work on scaffolding he designed himself. Pope Julius II had originally wanted twelve apostles, but Michelangelo convinced him to approve a far more ambitious scheme of 300 figures depicting Genesis. He returned decades later to paint <em>The Last Judgment</em> (1536-1541).` },
    { question: "What was Michelangelo's preferred medium?", answer: `He famously insisted he was a sculptor, not a painter, initially refusing Pope Julius II's commission. He believed sculpture was the supreme art because it freed figures from stone. His <em>David</em>, carved from a marble block other sculptors had abandoned, demonstrates his belief that figures existed within stone, waiting to be released.` },
    { question: "How old was Michelangelo when he died?", answer: `He lived to 88, extraordinarily rare for the era, dying in Rome in 1564 still working on the <em>Rondanini Pietà</em>. Though he wished to be buried in Rome, his nephew smuggled his body to Florence. He rests in Santa Croce, surrounded by other Florentine greats including Galileo and Machiavelli.` }
  ],

  "sanford-robinson-gifford": [
    { question: "What art movement was Sanford Robinson Gifford part of?", answer: `Gifford was a leading figure of the <a href="/apps/masterpieces/movement/hudson-river-school"><strong>Hudson River School</strong></a> and a master of <a href="/apps/masterpieces/movement/luminism"><strong>Luminism</strong></a>, the American style emphasizing atmospheric light effects. Unlike earlier Hudson River painters who focused on wilderness grandeur, Gifford painted light itself, stripping compositions to minimal landscape elements.` },
    { question: "Where can I see Sanford Robinson Gifford's paintings?", answer: `The <a href="/apps/masterpieces/museum/met"><strong>Metropolitan Museum of Art</strong></a>, which he co-founded, honored him with its first monographic retrospective in 1880. Works also hang at the National Gallery of Art, Smithsonian American Art Museum, and the Crystal Bridges Museum of American Art.` },
    { question: "What subjects did Sanford Robinson Gifford paint?", answer: `He painted <a href="https://luxurywallart.com/collections/landscapes" target="_blank" rel="noopener"><strong>atmospheric landscapes</strong></a> bathed in golden light, from the Catskills and Adirondacks to the Middle East and Egypt. His views of Lake Nemi in Italy and the Bosphorus in Turkey show his fascination with how light transforms scenery across different climates and times of day.` },
    { question: "Did Sanford Robinson Gifford serve in the Civil War?", answer: `Yes, driven by abolitionist convictions, he enlisted in New York's Seventh Regiment National Guard and served multiple deployments between 1861 and 1863. Unlike artists who observed from a distance, Gifford went as a soldier, not a correspondent. He sketched camp life and fortifications between active service.` },
    { question: "What technique made Gifford's paintings distinctive?", answer: `He applied multiple layers of tinted varnish over finished paintings to achieve his signature golden glow. This glazing technique unified compositions and created the illusion of light-filled atmosphere that earned him the nickname "the American Claude Lorrain." His skies seem to radiate warmth from within the canvas itself.` }
  ],

  "paula-modersohn-becker": [
    { question: "What art movement was Paula Modersohn-Becker part of?", answer: `She was an early German <a href="/apps/masterpieces/movement/expressionism"><strong>Expressionist</strong></a> who anticipated the movement before it had a name. Working in Worpswede, she rejected the colony's sentimental naturalism in favor of bold simplification influenced by Cézanne and Gauguin, whom she studied during four trips to Paris between 1900 and 1907.` },
    { question: "Where can I see Paula Modersohn-Becker's paintings?", answer: `The <strong>Paula Modersohn-Becker Museum</strong> in Bremen, opened in 1927, was the world's first museum dedicated to a woman artist. The <a href="/apps/masterpieces/museum/moma"><strong>Museum of Modern Art</strong></a> in New York, the Kunstmuseum Basel, and the Städel Museum in Frankfurt also hold significant works.` },
    { question: "What was groundbreaking about Modersohn-Becker's self-portraits?", answer: `She was the first known woman painter to create nude self-portraits. Her 1906 <em>Self-Portrait on the Sixth Wedding Anniversary</em> shows her pregnant (though she wasn't yet), naked to the waist, with unflinching directness. These radical <a href="https://luxurywallart.com/collections/portrait-art" target="_blank" rel="noopener"><strong>portraits</strong></a> claimed the female body for female artistic vision.` },
    { question: "How did Paula Modersohn-Becker die?", answer: `She died at 31, just eighteen days after giving birth to her daughter Mathilde, from a postpartum embolism. Following her doctor's instructions to remain in bed, she stood for the first time, said "What a pity," and collapsed. She left behind over 700 paintings and 1,400 drawings created in just fourteen years.` },
    { question: "What subjects did Modersohn-Becker paint?", answer: `She painted peasant women, children, and nursing mothers with simplified, monumental forms, rejecting sentimentality for psychological directness. Still lifes of fruit and flowers showed Cézanne's influence in their bold, flattened compositions. Her late work anticipates Expressionism by decades, making her posthumous reputation far exceed her recognition while alive.` }
  ],

  "william-trost-richards": [
    { question: "What art movements influenced William Trost Richards?", answer: `Richards transitioned from the <a href="/apps/masterpieces/movement/hudson-river-school"><strong>Hudson River School</strong></a> to <a href="/apps/masterpieces/movement/pre-raphaelitism"><strong>Pre-Raphaelitism</strong></a> after seeing an 1858 exhibition in Philadelphia. The English movement's demand for minute observation transformed his style from romantic generalization to almost photographic precision. He later became America's leading marine painter.` },
    { question: "Where can I see William Trost Richards's paintings?", answer: `The <a href="/apps/masterpieces/museum/met"><strong>Metropolitan Museum of Art</strong></a> holds acclaimed watercolors of the White Mountains. His work appears at the Philadelphia Museum of Art, Pennsylvania Academy of Fine Arts, Smithsonian American Art Museum, and the Thyssen-Bornemisza Museum in Madrid.` },
    { question: "What subjects did William Trost Richards paint?", answer: `His early career focused on woodland scenes with Pre-Raphaelite botanical precision. After 1867, he shifted to <a href="https://luxurywallart.com/collections/coastal-decor" target="_blank" rel="noopener"><strong>marine subjects</strong></a>: rocky coasts, crashing waves, and atmospheric seascapes along the Atlantic from New Jersey to Maine. His late works capture the drama of sea and weather with looser brushwork.` },
    { question: "Where did Richards live and work?", answer: `Born in Philadelphia, he remained based there but summered extensively on the coast. In 1881, he built "Graycliff" in Newport, Rhode Island, a clifftop home with studio overlooking the Atlantic. This vantage point allowed him to study waves, weather, and light for his remaining years. He died in Newport in 1905.` },
    { question: "What was Richards's contribution to American watercolor?", answer: `As a leading member of the American Watercolor Society, he helped elevate the medium from amateur pastime to serious art form. His watercolors of the White Mountains demonstrate technical virtuosity that rivals oil painting in luminosity and detail. Museums now prize these works as highly as his oils.` }
  ],

  "peter-paul-rubens": [
    { question: "What art movement was Peter Paul Rubens part of?", answer: `Rubens was the leading painter of the <a href="/apps/masterpieces/movement/baroque"><strong>Flemish Baroque</strong></a>, developing a style of exuberant energy, sensuous color, and dynamic movement that influenced European art for centuries. He combined Venetian colorism learned from Titian with the drama of Caravaggio and classical antiquity.` },
    { question: "Where can I see Peter Paul Rubens's paintings?", answer: `The <a href="/apps/masterpieces/museum/museo-del-prado"><strong>Prado</strong></a> in Madrid holds <em>The Three Graces</em> and many major works. Antwerp's Cathedral of Our Lady displays his altarpieces. The <strong>Rubenshuis</strong> in Antwerp, his home and studio, is now a museum. London's <a href="/apps/masterpieces/museum/national-gallery"><strong>National Gallery</strong></a> has significant works.` },
    { question: "How large was Rubens's workshop?", answer: `His Antwerp studio employed dozens of assistants and specialized painters who executed his designs. He might sketch compositions and paint key passages (faces, hands) while others completed backgrounds, drapery, and animals. Anthony van Dyck began as his assistant. This factory-like efficiency produced over 1,400 verified paintings.` },
    { question: "Was Rubens involved in diplomacy?", answer: `Yes, both Spain and England knighted him for diplomatic service. He negotiated peace between the two countries while painting for both courts. His 1628-1629 mission to Madrid, where he shared a studio with Velázquez, resulted in a treaty. Few artists combined artistic genius with statecraft at such levels.` },
    { question: "What defined Rubens's style?", answer: `His figures overflow with <a href="https://luxurywallart.com/collections/colorful-artwork" target="_blank" rel="noopener"><strong>vibrant flesh tones</strong></a>, sensuous curves, and dynamic movement. The term "Rubenesque" describes his full-bodied female forms, modeled on his second wife Helene Fourment. His brushwork ranges from delicate glazes to thick impasto, always serving emotional impact over finish.` }
  ],

  "paul-cezanne": [
    { question: "What art movement was Paul Cézanne part of?", answer: `Cézanne is classified as a <a href="/apps/masterpieces/movement/post-impressionism"><strong>Post-Impressionist</strong></a>, though he exhibited with the <a href="/apps/masterpieces/movement/impressionism"><strong>Impressionists</strong></a> early in his career. His analytical approach to form and color, treating nature as "the cylinder, the sphere, the cone," directly influenced <a href="/apps/masterpieces/movement/cubism"><strong>Cubism</strong></a>. Picasso called him "the father of us all."` },
    { question: "Where can I see Paul Cézanne's paintings?", answer: `Major collections include the <a href="/apps/masterpieces/museum/musee-dorsay"><strong>Musée d'Orsay</strong></a>, the Barnes Foundation in Philadelphia, and the Courtauld Gallery in London. The <a href="/apps/masterpieces/museum/met"><strong>Metropolitan Museum</strong></a> and Philadelphia Museum of Art hold significant Mont Sainte-Victoire paintings. His studio in Aix-en-Provence is preserved as a museum.` },
    { question: "Why did Cézanne paint Mont Sainte-Victoire so many times?", answer: `He created over 80 paintings and watercolors of the mountain near his hometown Aix-en-Provence. Each version explores how light, atmosphere, and viewpoint alter perception. Rather than capturing a single moment, he built form through overlapping planes of color, making the mountain a laboratory for his revolutionary approach to structure.` },
    { question: "What subjects did Cézanne paint?", answer: `He returned obsessively to still lifes (especially apples), bathers, portraits, and <a href="https://luxurywallart.com/collections/landscapes" target="_blank" rel="noopener"><strong>Provençal landscapes</strong></a>. His still lifes took so long that fruit rotted, so he switched to wax. His large <em>Bathers</em> compositions occupied him for years, attempting to integrate figures with landscape in a classical manner.` },
    { question: "Why was Cézanne important to modern art?", answer: `He broke from Impressionism's emphasis on fleeting effects to build solid, structural compositions. His technique of using color patches to construct form rather than merely describe light influenced Cubism, Fauvism, and abstract art. Matisse, Picasso, and Braque studied his work intensively, and exhibitions after his 1906 death changed art's direction.` }
  ],

  "fernand-leger": [
    { question: "What art movement was Fernand Léger part of?", answer: `Léger developed his own branch of <a href="/apps/masterpieces/movement/cubism"><strong>Cubism</strong></a> so distinctive that critic Louis Vauxcelles coined the term "Tubism" to describe it. His cylindrical, machine-like forms differed from Picasso and Braque's fragmented planes. He celebrated the beauty of modern machinery, technology, and urban life with bold primary colors.` },
    { question: "Where can I see Fernand Léger's paintings?", answer: `The <strong>Musée National Fernand Léger</strong> in Biot, France, opened in 1960, holds the largest collection. The <a href="/apps/masterpieces/museum/moma"><strong>Museum of Modern Art</strong></a> in New York, Centre Pompidou in Paris, and the Kröller-Müller Museum in the Netherlands all display major works.` },
    { question: "What subjects did Fernand Léger paint?", answer: `He painted <a href="https://luxurywallart.com/collections/abstract-wall-art" target="_blank" rel="noopener"><strong>mechanical forms</strong></a>, workers, and urban scenes celebrating modern life. After serving in World War I, where he was gassed, he became fascinated by machinery. His <em>Mechanical Elements</em> series depicts propellers, cylinders, and discs. Later work featured acrobats, construction workers, and bicyclists.` },
    { question: "Did Léger work in other media besides painting?", answer: `Yes, he directed and produced the experimental film <em>Ballet Mécanique</em> (1924), a pioneering work of abstract cinema with photography by Man Ray. He also designed sets for ballets and films, created ceramic murals, mosaics, and stained glass windows. His UN headquarters mosaic spans 800 square feet.` },
    { question: "How did military service affect Léger's art?", answer: `World War I transformed him. He wrote that fellow soldiers' slang and the beauty of artillery machinery opened his eyes. After surviving a gas attack at Verdun in 1917, he abandoned subtle colors for bold primaries and embraced the aesthetics of the industrial age. War made him "the painter of modern life."` }
  ],

  "gustave-courbet": [
    { question: "What art movement did Gustave Courbet lead?", answer: `Courbet was the founder and chief theorist of <a href="/apps/masterpieces/movement/realism"><strong>Realism</strong></a>, declaring that artists should only paint what they could see. In 1855, when the Exposition Universelle rejected his work, he built his own "Pavilion of Realism" nearby, staging one of art history's first one-man shows and writing a manifesto.` },
    { question: "Where can I see Gustave Courbet's paintings?", answer: `The <a href="/apps/masterpieces/museum/musee-dorsay"><strong>Musée d'Orsay</strong></a> in Paris holds <em>A Burial at Ornans</em>, <em>The Painter's Studio</em>, and <em>The Origin of the World</em> (not publicly displayed until 1995). The <strong>Musée Courbet</strong> in his hometown Ornans occupies his family's house. The <a href="/apps/masterpieces/museum/met"><strong>Metropolitan Museum</strong></a> has three dedicated rooms.` },
    { question: "Why was Courbet's art controversial?", answer: `He painted peasants and laborers at monumental scale previously reserved for history painting, offending academic hierarchies. <em>A Burial at Ornans</em> (1849-50) depicted a provincial funeral as twenty-two feet of blunt reality. His erotic works, including <em>The Origin of the World</em>, remained hidden for over a century.` },
    { question: "What happened to Courbet after the Paris Commune?", answer: `He joined the short-lived socialist government in 1871 and was blamed for toppling the Vendôme Column (a symbol of Napoleonic militarism). After the Commune's fall, he spent six months in prison and was ordered to pay for the column's reconstruction. He fled to Switzerland in 1873 and died in exile four years later.` },
    { question: "What subjects did Courbet paint?", answer: `He painted his native Franche-Comté region, hunting scenes, <a href="https://luxurywallart.com/collections/landscapes" target="_blank" rel="noopener"><strong>dramatic seascapes</strong></a>, <a href="https://luxurywallart.com/collections/women-art" target="_blank" rel="noopener"><strong>female nudes</strong></a>, and portraits. His landscapes of cliffs, caves, and forests around Ornans combine geological observation with Romantic grandeur. Everything he painted had physical presence, weight, and texture derived from direct observation.` }
  ],

  "piet-mondrian": [
    { question: "What art movement did Piet Mondrian found?", answer: `Mondrian co-founded <a href="/apps/masterpieces/movement/de-stijl"><strong>De Stijl</strong></a> (The Style) in 1917 with Theo van Doesburg and developed its theoretical foundation, which he called Neoplasticism. This radical abstraction reduced painting to horizontal and vertical black lines, primary colors (red, yellow, blue), and non-colors (white, black, gray) to express universal harmony.` },
    { question: "Where can I see Piet Mondrian's paintings?", answer: `The <strong>Kunstmuseum Den Haag</strong> (formerly Gemeentemuseum) in The Hague holds the world's largest Mondrian collection, including <em>Victory Boogie Woogie</em>. The <a href="/apps/masterpieces/museum/moma"><strong>Museum of Modern Art</strong></a> in New York has <em>Broadway Boogie Woogie</em>. London's <a href="/apps/masterpieces/museum/tate-modern"><strong>Tate Modern</strong></a> displays important works.` },
    { question: "How did Mondrian's style evolve?", answer: `He began as a traditional Dutch landscape painter before discovering Cubism in Paris around 1912. Through progressive abstraction, he eliminated curves, then reduced colors to primaries, arriving at his signature grid paintings by the 1920s. His final New York paintings added <a href="https://luxurywallart.com/collections/colorful-artwork" target="_blank" rel="noopener"><strong>vibrant colored lines</strong></a> and syncopated rhythms inspired by jazz.` },
    { question: "What influenced Mondrian's turn to abstraction?", answer: `Theosophy, a spiritual philosophy seeking universal truth, profoundly influenced him. He believed that reducing art to essential elements (vertical and horizontal lines, primary colors) could express cosmic harmony and balance. His geometric paintings weren't mere decoration but attempts to visualize spiritual and mathematical order underlying reality.` },
    { question: "Why did Mondrian move to New York?", answer: `He fled Paris for London in 1938, then left for New York in 1940 after a bomb fell near his studio. The city energized him. Broadway's grid pattern and jazz rhythms inspired his final masterpieces, <em>Broadway Boogie Woogie</em> and <em>Victory Boogie Woogie</em>, which replaced black lines with colored ones. He died there in 1944.` }
  ],

  "el-greco": [
    { question: "What art movement was El Greco part of?", answer: `El Greco worked during the late <a href="/apps/masterpieces/movement/renaissance"><strong>Renaissance</strong></a> but his elongated figures and intense colors align with <a href="/apps/masterpieces/movement/mannerism"><strong>Mannerism</strong></a>. His visionary, flame-like forms went beyond any contemporary style, and twentieth-century artists recognized him as a precursor to <a href="/apps/masterpieces/movement/expressionism"><strong>Expressionism</strong></a>.` },
    { question: "Where can I see El Greco's paintings?", answer: `Toledo, Spain, where he spent his final 37 years, holds the most works: the <strong>El Greco Museum</strong>, Santa Cruz Museum, and churches throughout the city. <em>The Burial of the Count of Orgaz</em> remains in Santo Tomé church. The <a href="/apps/masterpieces/museum/museo-del-prado"><strong>Prado</strong></a> and <a href="/apps/masterpieces/museum/met"><strong>Metropolitan Museum</strong></a> have major paintings.` },
    { question: "Why is El Greco called 'The Greek'?", answer: `Born Doménikos Theotokópoulos in Crete (then Venetian territory), he trained as an icon painter in the Byzantine tradition before moving to Venice and Rome. When he settled in Toledo in 1577, Spaniards simply called him "El Greco" (The Greek). He signed paintings in Greek letters until his death in 1614.` },
    { question: "What made El Greco's style distinctive?", answer: `His figures stretch impossibly upward, lit by cold, unearthly light. Colors clash dramatically: acid greens, electric blues, and stormy grays create <a href="https://luxurywallart.com/collections/spiritual-art" target="_blank" rel="noopener"><strong>visionary intensity</strong></a>. This style, considered bizarre in his era, later influenced Picasso and Pollock. Doctors once theorized (incorrectly) that he had astigmatism.` },
    { question: "What is El Greco's most famous painting?", answer: `<em>The Burial of the Count of Orgaz</em> (1586-88) in Toledo's Santo Tomé church depicts a miracle: Saints Stephen and Augustine descend from heaven to bury a pious nobleman while his soul rises above. The sixteen-foot canvas combines earthly portraits of Toledo's citizens with ethereal heavenly figures.` }
  ],

  "john-la-farge": [
    { question: "What was John La Farge known for?", answer: `La Farge revolutionized American art in multiple media. He's called the father of the <a href="/apps/masterpieces/movement/american-renaissance"><strong>American mural movement</strong></a> for his 1876 Trinity Church decorations in Boston. He also pioneered American stained glass, inventing opalescent glass and winning a patent in 1880 that established a new art form.` },
    { question: "Where can I see John La Farge's work?", answer: `His <em>Ascension</em> mural (1887) fills the Church of the Ascension in New York City. Stained glass windows appear at Trinity Church Boston, the Biltmore Estate, and Columbia University's St. Paul's Chapel. Paintings hang at the <a href="/apps/masterpieces/museum/met"><strong>Metropolitan Museum</strong></a>, Museum of Fine Arts Boston, and Smithsonian American Art Museum.` },
    { question: "What innovation did La Farge bring to stained glass?", answer: `He invented opalescent glass, which incorporated color within the glass itself rather than relying on painted details. This created richer <a href="https://luxurywallart.com/collections/colorful-artwork" target="_blank" rel="noopener"><strong>color effects</strong></a> and greater luminosity. His 1880 patent and 1889 Paris Exposition gold medal established American leadership in decorative glass, influencing Louis Comfort Tiffany.` },
    { question: "Did John La Farge travel extensively?", answer: `Yes, his 1886 trip to Japan with writer Henry Adams profoundly influenced his art, introducing him to Japanese aesthetics. He later traveled to the South Pacific (1890-91), where he painted Tahitian and Samoan subjects that anticipated Gauguin's work. His travel writings and watercolors documented vanishing cultures.` },
    { question: "How prolific was John La Farge?", answer: `Over his lifetime he produced approximately 250 oil paintings, a dozen major mural cycles, 400 stained glass windows, 4,000 drawings, and 1,200 watercolors. He co-founded the Society of American Artists and served as president of the National Society of Mural Painters. France awarded him the Legion of Honor.` }
  ],

  "albrecht-durer": [
    { question: "What art movement was Albrecht Dürer part of?", answer: `Dürer was the leading artist of the Northern <a href="/apps/masterpieces/movement/renaissance"><strong>Renaissance</strong></a>, bridging Gothic tradition and Italian humanist ideals. His two trips to Italy (1494-95, 1505-07) transformed German art, while his theoretical writings on proportion and perspective brought Renaissance principles north of the Alps.` },
    { question: "Where can I see Albrecht Dürer's works?", answer: `The <strong>Albrecht-Dürer-Haus</strong> in Nuremberg, his home from 1509, is now a museum. Major paintings hang at the <a href="/apps/masterpieces/museum/alte-pinakothek"><strong>Alte Pinakothek</strong></a> in Munich and Vienna's Kunsthistorisches Museum. The <a href="/apps/masterpieces/museum/met"><strong>Metropolitan Museum</strong></a> and British Museum hold extensive print collections.` },
    { question: "Why are Dürer's prints so significant?", answer: `He elevated printmaking from craft to fine art. His woodcuts and engravings achieved unprecedented tonal range and technical brilliance, spreading his fame across Europe. Works like <em>Knight, Death and the Devil</em>, <em>Melencolia I</em>, and <em>St. Jerome in His Study</em> (all 1513-14) remain among the greatest prints ever made.` },
    { question: "What subjects did Dürer paint and engrave?", answer: `Religious subjects, <a href="https://luxurywallart.com/collections/portrait-art" target="_blank" rel="noopener"><strong>portraits</strong></a>, self-portraits, and nature studies. His self-portraits chronicle his life from age 13 to 28. His <em>Young Hare</em> and <em>Great Piece of Turf</em> watercolors demonstrate microscopic observation. His <em>Rhinoceros</em> woodcut (made without seeing the animal) remained influential for centuries.` },
    { question: "What was Dürer's relationship with Maximilian I?", answer: `From 1512, Emperor Maximilian I became his patron, commissioning major projects including the <em>Triumphal Arch</em>, a massive woodcut composed of 192 separate blocks. The emperor granted Dürer an annual pension of 100 florins, continued by Charles V. This imperial patronage brought prestige and financial security.` }
  ],

  "paul-gauguin": [
    { question: "What art movement was Paul Gauguin part of?", answer: `Gauguin was a central figure in <a href="/apps/masterpieces/movement/post-impressionism"><strong>Post-Impressionism</strong></a> and <a href="/apps/masterpieces/movement/symbolism"><strong>Symbolism</strong></a>. At Pont-Aven in Brittany, he developed Synthetism with Émile Bernard, using flat areas of bold color separated by dark outlines. His primitivist style influenced Fauvism and Expressionism.` },
    { question: "Where can I see Paul Gauguin's paintings?", answer: `<em>Where Do We Come From? What Are We? Where Are We Going?</em> is at the Museum of Fine Arts, Boston. The <a href="/apps/masterpieces/museum/musee-dorsay"><strong>Musée d'Orsay</strong></a> in Paris holds major works. The <a href="/apps/masterpieces/museum/art-institute-chicago"><strong>Art Institute of Chicago</strong></a>, Van Gogh Museum Amsterdam, and <a href="/apps/masterpieces/museum/moma"><strong>MoMA</strong></a> display significant paintings.` },
    { question: "Why did Gauguin go to Tahiti?", answer: `Disillusioned with European civilization and seeking "primitive" authenticity, he sailed to Tahiti in 1891 at age 43. He found the island already colonized and missionaries had suppressed indigenous culture. Still, he created <a href="https://luxurywallart.com/collections/tropical-art" target="_blank" rel="noopener"><strong>tropical scenes</strong></a> combining real observation with invented mythology that defined his mature work.` },
    { question: "What was Gauguin's relationship with Van Gogh?", answer: `Vincent van Gogh invited him to Arles in 1888 to establish an artists' colony. Their nine-week cohabitation ended disastrously after fierce arguments about art. The night Van Gogh cut off part of his ear, Gauguin fled. They never met again, though Van Gogh's brother Theo continued representing Gauguin.` },
    { question: "What was Gauguin's career before art?", answer: `He worked as a successful stockbroker in Paris, painting only as a hobby and collecting Impressionist works. The 1882 stock market crash ended his financial career. He abandoned his Danish wife and five children to pursue art full-time, a choice that haunted but never deterred him.` }
  ],

  "parmigianino": [
    { question: "What art movement was Parmigianino part of?", answer: `Parmigianino was a leading painter of <a href="/apps/masterpieces/movement/mannerism"><strong>Mannerism</strong></a>, the sophisticated style that followed the High Renaissance. His elongated figures, complex poses, and refined elegance exemplify Mannerist ideals. Vasari wrote that in Rome he was "celebrated as a Raphael reborn," before developing his distinctive artificial grace.` },
    { question: "Where can I see Parmigianino's paintings?", answer: `<em>Madonna with the Long Neck</em> hangs at the <a href="/apps/masterpieces/museum/uffizi"><strong>Uffizi Gallery</strong></a> in Florence. The <a href="/apps/masterpieces/museum/national-gallery"><strong>National Gallery</strong></a> in London has <em>Vision of Saint Jerome</em>. Naples' Capodimonte Museum holds fine portraits including <em>Antea</em>. The <a href="/apps/masterpieces/museum/museo-del-prado"><strong>Prado</strong></a> and Kunsthistorisches Museum Vienna also have works.` },
    { question: "What is the Madonna with the Long Neck?", answer: `This unfinished altarpiece (c. 1535-40), now at the <a href="/apps/masterpieces/museum/uffizi"><strong>Uffizi</strong></a>, epitomizes Mannerist elegance. The Virgin's impossibly elongated neck, fingers, and the strangely stretched Christ Child deliberately violate natural proportion for aesthetic effect. The tiny prophet in the background heightens the distortion. Parmigianino worked on it for six years without finishing.` },
    { question: "Why did Parmigianino die young?", answer: `He died at 37 in 1540, having grown, according to Vasari, "bearded, long-haired, and neglected" from obsession with alchemy. He spent his final years seeking to transmute base metals into gold rather than painting, leaving the <em>Madonna with the Long Neck</em> incomplete. The pursuit bankrupted him and destroyed his health.` },
    { question: "What subjects did Parmigianino paint?", answer: `Religious altarpieces, mythological scenes, and <a href="https://luxurywallart.com/collections/portrait-art" target="_blank" rel="noopener"><strong>elegant portraits</strong></a> of Italian nobility. His self-portrait in a convex mirror (now in Vienna) demonstrates technical virtuosity, painting his own distorted reflection. His graceful figures influenced artists for generations, from the Fontainebleau School to the later Baroque.` }
  ],

  "pierre-bonnard": [
    { question: "What art movement was Pierre Bonnard part of?", answer: `Bonnard was a founding member of <a href="/apps/masterpieces/movement/les-nabis"><strong>Les Nabis</strong></a> in 1889, the Post-Impressionist group influenced by Gauguin. He later became a leader of Intimism, painting domestic scenes with rich, shimmering color. His work bridges Impressionism and later color-field abstraction.` },
    { question: "Where can I see Pierre Bonnard's paintings?", answer: `The <strong>Phillips Collection</strong> in Washington, D.C. has one of the largest Bonnard collections outside France, over 30 works. The <a href="/apps/masterpieces/museum/musee-dorsay"><strong>Musée d'Orsay</strong></a>, Centre Pompidou, and the <strong>Musée Bonnard</strong> in Le Cannet (where he died) hold major works. <a href="/apps/masterpieces/museum/moma"><strong>MoMA</strong></a> has significant paintings.` },
    { question: "What subjects did Pierre Bonnard paint?", answer: `He painted intimate domestic scenes: breakfast tables, gardens, bathrooms, his wife Marthe bathing. Over decades, Marthe appears in hundreds of paintings. His <a href="https://luxurywallart.com/collections/colorful-artwork" target="_blank" rel="noopener"><strong>saturated colors</strong></a> transform ordinary interiors into shimmering fields of light. Landscapes of Normandy and the South of France also feature prominently.` },
    { question: "What was distinctive about Bonnard's painting method?", answer: `He rarely painted from life, preferring to sketch subjects and work from memory in the studio. This allowed him to concentrate on the emotional essence rather than literal appearance. He applied paint in small, mosaic-like touches, building up layers of close-valued color that create optical vibrancy.` },
    { question: "How did Bonnard's wife influence his art?", answer: `Marthe de Méligny (born Maria Boursin) modeled for Bonnard from 1893 until her death in 1942. She appears in hundreds of paintings, often bathing or at her toilette. Even as she aged, Bonnard painted her with a youthful body, creating an eternal, idealized presence that transcends documentation.` }
  ],

  "odilon-redon": [
    { question: "What art movement was Odilon Redon part of?", answer: `Redon was a leading figure in <a href="/apps/masterpieces/movement/symbolism"><strong>Symbolism</strong></a>, creating dreamlike imagery that influenced the Surrealists decades later. André Breton championed his work. His art divided into two phases: dark charcoal "noirs" exploring nightmares and macabre themes, followed by radiant pastels of flowers and mythological subjects.` },
    { question: "Where can I see Odilon Redon's paintings?", answer: `The <a href="/apps/masterpieces/museum/musee-dorsay"><strong>Musée d'Orsay</strong></a> holds major works from both periods. The <a href="/apps/masterpieces/museum/moma"><strong>Museum of Modern Art</strong></a> in New York owns significant pieces. The Kröller-Müller Museum in the Netherlands and the <a href="/apps/masterpieces/museum/art-institute-chicago"><strong>Art Institute of Chicago</strong></a> display important examples.` },
    { question: "What were Redon's 'noirs'?", answer: `His "noirs" (blacks) were charcoal drawings and lithographs created from the 1870s to 1890s, depicting floating eyeballs, strange hybrids, and <a href="https://luxurywallart.com/collections/macabre-art" target="_blank" rel="noopener"><strong>macabre visions</strong></a>. Titles like <em>The Eye, Like a Strange Balloon, Mounts Toward Infinity</em> suggest their hallucinatory character. After 1890, he abandoned black for explosive color.` },
    { question: "What subjects did Redon paint in color?", answer: `After 1900, he focused on <a href="https://luxurywallart.com/collections/floral-art" target="_blank" rel="noopener"><strong>vibrant flower bouquets</strong></a>, mythological figures like Ophelia and Orpheus, and butterflies. His pastels achieve jewel-like intensity. The shift coincided with personal happiness: his son's birth after years of childlessness and increasing recognition of his work.` },
    { question: "How did Redon influence later artists?", answer: `The Nabis (Bonnard, Vuillard) acknowledged his impact on their development. Matisse credited Redon's pastels with influencing his Fauvist palette. The Surrealists later embraced his dream imagery. His path from dark psychological depths to radiant color anticipated artistic directions he never lived to see fully realized.` }
  ],

  "raphael": [
    { question: "What art movement was Raphael part of?", answer: `Raphael was a supreme master of the <a href="/apps/masterpieces/movement/renaissance"><strong>High Renaissance</strong></a>, forming the traditional trinity of great masters with Leonardo da Vinci and Michelangelo. His balanced compositions, harmonious figures, and idealized beauty defined Renaissance ideals. His clarity and grace influenced Western art for centuries.` },
    { question: "Where can I see Raphael's paintings?", answer: `The <a href="/apps/masterpieces/museum/vatican-museums"><strong>Vatican Museums</strong></a> contain the Raphael Rooms (Stanze di Raffaello), including <em>The School of Athens</em>. The <em>Sistine Madonna</em> is in Dresden's Gemäldegalerie Alte Meister. The <a href="/apps/masterpieces/museum/uffizi"><strong>Uffizi</strong></a>, <a href="/apps/masterpieces/museum/museo-del-prado"><strong>Prado</strong></a>, <a href="/apps/masterpieces/museum/louvre"><strong>Louvre</strong></a>, and <a href="/apps/masterpieces/museum/national-gallery"><strong>National Gallery</strong></a> hold major works.` },
    { question: "What is The School of Athens?", answer: `This fresco (1509-11) in the Vatican's Stanza della Segnatura depicts ancient philosophers gathered around Plato and Aristotle. Raphael portrayed Plato with Leonardo's features and included himself among the crowd. The perfectly balanced composition and architectural setting epitomize High Renaissance ideals of harmony and classical learning.` },
    { question: "How many Madonnas did Raphael paint?", answer: `He painted approximately forty <a href="https://luxurywallart.com/collections/spiritual-art" target="_blank" rel="noopener"><strong>Madonna and Child compositions</strong></a>, making the subject his signature theme. From intimate Florentine devotional images to the monumental <em>Sistine Madonna</em> commissioned by Pope Julius II, these works set standards for religious painting that influenced artists for centuries.` },
    { question: "How did Raphael die?", answer: `He died on his 37th birthday, April 6, 1520, possibly from exhaustion or illness after intense creative output. Vasari blamed excessive romantic activities. His funeral at the Vatican was attended by enormous crowds. He was buried in the Pantheon in Rome, where his tomb remains a pilgrimage site.` }
  ],

  "adolph-menzel": [
    { question: "What art movement was Adolph Menzel part of?", answer: `Menzel was Germany's most important <a href="/apps/masterpieces/movement/realism"><strong>Realist</strong></a> painter, committed to objective, true-to-life representation. Unlike Romantic painters like Caspar David Friedrich, he rejected idealization for direct observation. His range spanned history painting, industrial scenes, and intimate interiors with equal commitment to factual accuracy.` },
    { question: "Where can I see Adolph Menzel's paintings?", answer: `The <a href="/apps/masterpieces/museum/alte-nationalgalerie"><strong>Alte Nationalgalerie</strong></a> in Berlin holds most of his major works and hosted his 80th birthday retrospective in 1895. Munich's Neue Pinakothek and the Kupferstichkabinett (Museum of Prints and Drawings) in Berlin have significant collections. A 1996-97 retrospective traveled to Paris's Musée d'Orsay and Washington's National Gallery.` },
    { question: "What were Menzel's Frederick the Great paintings?", answer: `He created 400 drawings illustrating Franz Kugler's <em>History of Frederick the Great</em> (1839-42), establishing his reputation. Later paintings like <em>The Flute Concert at Sanssouci</em> (1852) show Frederick in private moments rather than military glory. These humanized <a href="https://luxurywallart.com/collections/portrait-art" target="_blank" rel="noopener"><strong>historical scenes</strong></a> subverted expectations of courtly propaganda.` },
    { question: "What made Menzel's style distinctive?", answer: `His obsessive attention to detail and willingness to paint unglamorous subjects set him apart. <em>The Iron Rolling Mill</em> (1875) depicts sweating workers in a factory with documentary precision unprecedented in fine art. Small paintings of empty rooms, rumpled bedsheets, and random corners demonstrate equal interest in overlooked subjects.` },
    { question: "What honors did Adolph Menzel receive?", answer: `In 1898, he became the first painter admitted to Prussia's Order of the Black Eagle, which elevated him to nobility (becoming "von Menzel"). The Académie des Beaux-Arts in Paris and London's Royal Academy also made him a member. When he died in 1905, Kaiser Wilhelm II directed his state funeral.` }
  ],

  "guido-reni": [
    { question: "What art movement was Guido Reni part of?", answer: `Reni was a leading painter of the Italian <a href="/apps/masterpieces/movement/baroque"><strong>Baroque</strong></a>, though his classically restrained style contrasts with Caravaggio's drama. He trained with the Carracci in Bologna before moving to Rome. His idealized figures and silvery palette made him the most sought-after religious painter of his generation.` },
    { question: "Where can I see Guido Reni's paintings?", answer: `His <em>Aurora</em> fresco adorns Casino dell'Aurora at Palazzo Pallavicini-Rospigliosi in Rome. Bologna's National Art Gallery holds major altarpieces. The <a href="/apps/masterpieces/museum/louvre"><strong>Louvre</strong></a>, <a href="/apps/masterpieces/museum/museo-del-prado"><strong>Prado</strong></a>, and <a href="/apps/masterpieces/museum/national-gallery"><strong>National Gallery</strong></a> in London display important works. The <a href="/apps/masterpieces/museum/met"><strong>Metropolitan Museum</strong></a> has <em>Charity</em> and other pieces.` },
    { question: "What is Guido Reni's Aurora fresco?", answer: `Painted 1613-14 for Cardinal Scipione Borghese, this ceiling fresco shows Aurora (Dawn) leading Apollo's chariot across the sky, surrounded by dancing Hours. Its classical restraint, influenced by Raphael and ancient art, contrasts with contemporary Baroque exuberance. The fresco remains in the Palazzo Pallavicini-Rospigliosi in Rome.` },
    { question: "What subjects did Guido Reni paint?", answer: `Primarily <a href="https://luxurywallart.com/collections/spiritual-art" target="_blank" rel="noopener"><strong>religious subjects</strong></a>: Madonnas, saints in ecstasy, and biblical scenes rendered with idealized beauty. His weeping Magdalenes and suffering Christs combine emotional intensity with classical restraint. He also painted mythological scenes and portraits. His workshop in Bologna trained nearly 200 pupils.` },
    { question: "Why did Reni's reputation decline and revive?", answer: `The most famous Italian artist of his generation, Reni fell from favor in the 19th century when critics deemed his work too sweet and sentimental. John Ruskin called him a "sentimentalist." Twentieth-century scholarship restored appreciation for his technical mastery, psychological subtlety, and historical importance.` }
  ],

  "canaletto": [
    { question: "What was Canaletto known for painting?", answer: `Canaletto specialized in <strong>vedute</strong> (view paintings), precisely detailed cityscapes of Venice that made him the most sought-after artist among British Grand Tourists. His topographical accuracy, atmospheric effects, and sparkling light on water created the defining images of 18th-century Venice that still shape our perception of the city.` },
    { question: "Where can I see Canaletto's paintings?", answer: `The British Royal Collection holds 50 paintings and 142 drawings, purchased from Canaletto's agent Joseph Smith in 1762. The <a href="/apps/masterpieces/museum/national-gallery"><strong>National Gallery</strong></a> in London, Wallace Collection, and Woburn Abbey have major works. The <a href="/apps/masterpieces/museum/met"><strong>Metropolitan Museum</strong></a> and <a href="/apps/masterpieces/museum/uffizi"><strong>Uffizi</strong></a> display important paintings.` },
    { question: "Did Canaletto use a camera obscura?", answer: `Probably yes. This optical device projected images onto a surface, helping achieve his extraordinary precision. He would sketch Venice's architecture with rulers, drawing perspective lines in pencil before adding detail. His mathematically precise <a href="https://luxurywallart.com/collections/landscapes" target="_blank" rel="noopener"><strong>cityscapes</strong></a> combine topographical accuracy with luminous atmosphere.` },
    { question: "Why did Canaletto move to England?", answer: `The War of Austrian Succession (1740s) reduced British tourism to Venice, collapsing his market. From 1746 to 1755, he lived in London, painting views of the Thames, Westminster, and his patrons' country estates. These English views, though accomplished, never matched his Venetian work's atmospheric brilliance.` },
    { question: "What was Canaletto's most important early painting?", answer: `<em>The Stonemason's Yard</em> (c. 1725), now at the <a href="/apps/masterpieces/museum/national-gallery"><strong>National Gallery</strong></a> in London, shows a humble working scene rather than famous landmarks. Its intimate scale and atmospheric subtlety differ from his later, more formulaic tourist views. Critics consider it among his finest, most personal works.` }
  ],

  "henri-toulouse-lautrec": [
    { question: "What art movement was Toulouse-Lautrec part of?", answer: `Toulouse-Lautrec worked during the <a href="/apps/masterpieces/movement/post-impressionism"><strong>Post-Impressionist</strong></a> era, influenced by Degas's compositions and Japanese prints. His bold outlines, flat color areas, and dynamic movement anticipated Art Nouveau. He elevated commercial lithography to fine art, revolutionizing poster design while documenting Montmartre's nightlife.` },
    { question: "Where can I see Toulouse-Lautrec's work?", answer: `The <strong>Musée Toulouse-Lautrec</strong> in Albi, his birthplace, holds the world's largest collection: 219 paintings, 563 drawings, and 183 lithographs. The <a href="/apps/masterpieces/museum/musee-dorsay"><strong>Musée d'Orsay</strong></a> displays major paintings. The <a href="/apps/masterpieces/museum/art-institute-chicago"><strong>Art Institute of Chicago</strong></a> and <a href="/apps/masterpieces/museum/moma"><strong>MoMA</strong></a> have significant works.` },
    { question: "What was Toulouse-Lautrec's connection to the Moulin Rouge?", answer: `When the cabaret opened in 1889, his painting hung near the entrance. In 1891, his six-foot-tall poster of dancer La Goulue made him famous overnight; 3,000 copies appeared across Paris one evening. He became a fixture there, documenting performers like Jane Avril and Yvette Guilbert with <a href="https://luxurywallart.com/collections/portrait-art" target="_blank" rel="noopener"><strong>penetrating portraits</strong></a>.` },
    { question: "What physical challenges did Toulouse-Lautrec face?", answer: `Born into one of France's oldest noble families, he suffered from a genetic condition (likely pycnodysostosis) that stunted his leg growth after childhood fractures. His adult height was about 4 feet 8 inches. This disability distanced him from aristocratic life and drew him to Montmartre's marginalized performers and prostitutes.` },
    { question: "How did Toulouse-Lautrec die?", answer: `Alcoholism and syphilis destroyed his health. He suffered a stroke at 36 and died at his family's Château Malromé in 1901, three months before his 37th birthday. Despite his short life, he left 737 canvases, 275 watercolors, 363 prints and posters, and over 5,000 drawings documenting Belle Époque Paris.` }
  ],

  "dante-gabriel-rossetti": [
    { question: "What art movement did Dante Gabriel Rossetti found?", answer: `In 1848, Rossetti co-founded the <a href="/apps/masterpieces/movement/pre-raphaelitism"><strong>Pre-Raphaelite Brotherhood</strong></a> with John Everett Millais and William Holman Hunt. They rejected Royal Academy conventions for "truth to nature" and medieval inspiration. Rossetti later pioneered Aestheticism, emphasizing beauty for its own sake, influencing Art Nouveau.` },
    { question: "Where can I see Dante Gabriel Rossetti's paintings?", answer: `<a href="/apps/masterpieces/museum/tate-britain"><strong>Tate Britain</strong></a> in London holds the most significant collection, including <em>Proserpine</em> and <em>The Girlhood of Mary Virgin</em>. The Delaware Art Museum has major works. The Birmingham Museum and Art Gallery and the Ashmolean Museum in Oxford display important paintings.` },
    { question: "Was Rossetti also a poet?", answer: `Yes, he considered himself a poet first. His verse, like "The Blessed Damozel" and the sonnet sequence <em>The House of Life</em>, closely relates to his painting. He buried his unpublished poems with his wife Elizabeth Siddal in 1862, then controversially exhumed them for publication in 1869.` },
    { question: "What subjects did Rossetti paint?", answer: `Medieval romance, literary subjects (Dante's <em>Vita Nuova</em>, Shakespeare, Tennyson), and <a href="https://luxurywallart.com/collections/women-art" target="_blank" rel="noopener"><strong>sensuous female figures</strong></a> with flowing hair and full lips. His later work features idealized women surrounded by symbolic flowers. Jane Morris, wife of William Morris, modeled for his most iconic paintings including <em>Proserpine</em>.` },
    { question: "What was Rossetti's relationship with Elizabeth Siddal?", answer: `She modeled for Pre-Raphaelite paintings (including Millais's <em>Ophelia</em>) before becoming Rossetti's exclusive model and muse. They married in 1860 after a decade-long relationship. She died of a laudanum overdose in 1862, possibly suicide. Her death haunted Rossetti, who was later plagued by insomnia, chloral addiction, and paranoia.` }
  ],

  "albert-marquet": [
    { question: "What art movement was Albert Marquet part of?", answer: `Marquet was a founding member of <a href="/apps/masterpieces/movement/fauvism"><strong>Fauvism</strong></a>, exhibiting alongside Matisse, Derain, and Vlaminck at the scandalous 1905 Salon d'Automne. However, he used more subdued colors than his colleagues and soon moved toward naturalistic landscapes. His close friendship with Matisse began in student days.` },
    { question: "Where can I see Albert Marquet's paintings?", answer: `The <a href="/apps/masterpieces/museum/musee-dorsay"><strong>Musée d'Orsay</strong></a> in Paris and the Musée d'Art Moderne de Paris hold important works. The <a href="/apps/masterpieces/museum/hermitage"><strong>Hermitage</strong></a> in St. Petersburg, <a href="/apps/masterpieces/museum/tate-modern"><strong>Tate</strong></a> in London, and <a href="/apps/masterpieces/museum/art-institute-chicago"><strong>Art Institute of Chicago</strong></a> also display his paintings.` },
    { question: "What subjects did Albert Marquet paint?", answer: `He painted <a href="https://luxurywallart.com/collections/coastal-decor" target="_blank" rel="noopener"><strong>harbors, rivers, and coastlines</strong></a> throughout his life: the Seine in Paris, ports along the Mediterranean, Venice's lagoon, Naples, and Algiers (where he spent winters after 1920). Water fascinated him; he painted it as a flat plane of unified tone rather than impressionist shimmer.` },
    { question: "How did Marquet paint water differently from Impressionists?", answer: `Rather than breaking water into colored reflections, he rendered it as large areas of single, harmonized tone. This radical simplification held the water's surface without illusionistic depth. His economical brushwork captures light on water with remarkable directness, anticipating later abstraction while remaining faithful to observation.` },
    { question: "What was Marquet's friendship with Matisse like?", answer: `They met as teenagers at Paris's École des Arts Décoratifs and remained lifelong friends despite different artistic directions. As early as 1898, they painted together using pure colors that anticipated Fauvism. After Marquet moved toward naturalism, Matisse called him "our Hokusai," praising his subtle simplification.` }
  ]
};

async function main() {
  console.log("Expanding FAQs for 25 artists (35-60 words with interlinks)...\n");

  let updated = 0;
  let notFound = 0;

  for (const [slug, faqs] of Object.entries(artistFAQs)) {
    const artist = await prisma.artist.findUnique({ where: { slug } });
    if (artist) {
      await prisma.artist.update({
        where: { slug },
        data: {
          faqs: faqs,
          updatedAt: new Date()
        }
      });
      console.log(`✓ Updated: ${artist.name} (${faqs.length} FAQs)`);
      updated++;
    } else {
      console.log(`✗ Not found: ${slug}`);
      notFound++;
    }
  }

  console.log(`\nUpdated ${updated} artists, ${notFound} not found`);
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
