import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Batch 6: 10 artists (franz-marc through andre-derain)
const artistUpdates: Record<string, { bioFull: string; faqs: { question: string; answer: string }[] }> = {
  "franz-marc": {
    bioFull: `<p><strong>Franz Marc</strong> (1880–1916) painted animals with a spiritual intensity that set him apart from every other German <a href="/movement/expressionism"><strong>Expressionist</strong></a>. Born in Munich to a landscape painter father, he studied at the Academy of Fine Arts before two trips to Paris exposed him to Van Gogh and the Post-Impressionists. In 1911, he co-founded Der Blaue Reiter (The Blue Rider) with Wassily Kandinsky, a group that rejected naturalism in favor of color as pure emotion. Marc assigned symbolic meaning to his palette: blue represented masculinity and spirituality, yellow stood for feminine joy, red conveyed violence.</p>

<p>His subjects were almost exclusively animals, which he believed possessed a purity and innocence that modern humans had lost. Horses, deer, foxes, and tigers appear in bold, fragmented compositions influenced by <a href="/movement/cubism"><strong>Cubism</strong></a> and Futurism. Major works like <em>The Tower of Blue Horses</em> (1913), <em>The Foxes</em> (1913), and <em>Fate of the Animals</em> (1913) show his move toward abstraction. When World War I began, Marc enlisted in the German cavalry. The government later compiled a list of notable artists to withdraw from combat, but before the orders reached him, a shell splinter struck him in the head during the Battle of Verdun. He was thirty-six. The Nazis labeled his work "degenerate" in the 1930s, but most survived. In 2022, <em>The Foxes</em> sold for £42.6 million. Today his paintings hang in the <a href="/museum/neue-pinakothek"><strong>Neue Pinakothek</strong></a> in Munich and the <a href="/museum/solomon-r-guggenheim-museum"><strong>Guggenheim Museum</strong></a> in New York.</p>`,
    faqs: [
      { question: "What art movement was Franz Marc part of?", answer: `Marc was a leading German <a href="/movement/expressionism"><strong>Expressionist</strong></a> and co-founder of Der Blaue Reiter (The Blue Rider) in 1911 with Wassily Kandinsky. The group emphasized spiritual meaning through bold color.` },
      { question: "Where can I see Franz Marc's paintings?", answer: `Major collections are at the <a href="/museum/neue-pinakothek"><strong>Neue Pinakothek</strong></a> in Munich, the <a href="/museum/solomon-r-guggenheim-museum"><strong>Guggenheim Museum</strong></a> in New York, and the Städel Museum in Frankfurt.` },
      { question: "What subjects did Franz Marc paint?", answer: `Marc painted almost exclusively <a href="https://luxurywallart.com/collections/animal-art" target="_blank" rel="noopener"><strong>animals</strong></a>, especially horses, deer, foxes, and tigers. He believed animals had spiritual purity that humans lacked.` },
      { question: "What did the colors mean in Franz Marc's paintings?", answer: `Marc assigned symbolic meanings to colors: <a href="https://luxurywallart.com/collections/blue-wall-art" target="_blank" rel="noopener"><strong>blue</strong></a> represented masculinity and spirituality, <a href="https://luxurywallart.com/collections/yellow-paintings" target="_blank" rel="noopener"><strong>yellow</strong></a> meant feminine joy, and <a href="https://luxurywallart.com/collections/red-wall-art" target="_blank" rel="noopener"><strong>red</strong></a> conveyed violence.` },
      { question: "How did Franz Marc die?", answer: `Marc was killed at the <strong>Battle of Verdun</strong> on March 4, 1916. A shell splinter struck him in the head before military orders to withdraw him from combat could arrive.` },
      { question: "What are Franz Marc's most famous paintings?", answer: `His best-known works include <em>The Tower of Blue Horses</em> (1913), <em>The Foxes</em> (1913), and <em>Fate of the Animals</em> (1913). <strong><em>The Foxes</em></strong> sold for £42.6 million in 2022.` }
    ]
  },

  "giovanni-battista-tiepolo": {
    bioFull: `<p><strong>Giovanni Battista Tiepolo</strong> (1696–1770) was the last great painter of the Italian <a href="/movement/rococo"><strong>Rococo</strong></a> and the finest fresco artist of his century. Born in Venice, he trained under Gregorio Lazzarini and absorbed the legacy of Tintoretto and Veronese. By age twenty he was already working on church ceiling commissions. His palette lightened over time, and his compositions grew increasingly airy and theatrical, with figures floating in luminous skies surrounded by billowing clouds and classical architecture.</p>

<p>Tiepolo's fame spread across Europe. From 1750 to 1753, he worked for Prince-Bishop Carl Philipp von Greiffenklau at the Würzburg Residence in Germany, painting the largest fresco in the world over the grand staircase designed by Balthasar Neumann. The ceiling shows Apollo surrounded by allegorical figures representing the four continents. In 1761, Spain's King Charles III summoned him to Madrid to decorate the Royal Palace. There he faced opposition from the rising Neoclassicist Anton Raphael Mengs, whose austere style was overtaking the Rococo. Tiepolo died in Madrid in 1770. His sons Domenico and Lorenzo assisted him throughout his career. A contemporary called him "the most famous of the virtuosi," and Michael Levey later described him as "the greatest decorative painter of eighteenth-century Europe." His easel paintings and oil sketches can be found at the <a href="/museum/met"><strong>Metropolitan Museum of Art</strong></a>, the <a href="/museum/national-gallery"><strong>National Gallery</strong></a> in London, and the <a href="/museum/prado"><strong>Museo del Prado</strong></a>.</p>`,
    faqs: [
      { question: "What art movement was Giovanni Battista Tiepolo part of?", answer: `Tiepolo was the foremost painter of the <a href="/movement/rococo"><strong>Rococo</strong></a> period, known for his airy, luminous ceiling frescoes filled with classical and religious subjects.` },
      { question: "Where can I see Tiepolo's paintings?", answer: `His frescoes are in the <strong>Würzburg Residence</strong> in Germany and the <strong>Royal Palace of Madrid</strong>. Easel paintings hang at the <a href="/museum/met"><strong>Metropolitan Museum of Art</strong></a> and the <a href="/museum/prado"><strong>Museo del Prado</strong></a>.` },
      { question: "What is Tiepolo's most famous work?", answer: `His ceiling fresco in the <strong>Würzburg Residence</strong> (1750–1753), showing Apollo and allegories of the four continents, is considered the largest fresco in the world.` },
      { question: "Where did Tiepolo work outside Italy?", answer: `Tiepolo worked in <strong>Germany</strong> for the Prince-Bishop of Würzburg (1750–1753) and in <strong>Spain</strong> for King Charles III at the Royal Palace of Madrid (1761–1770).` },
      { question: "Who were Tiepolo's sons?", answer: `His sons <strong>Domenico</strong> and <strong>Lorenzo Tiepolo</strong> worked as his assistants. Domenico became a respected painter himself, known for his own frescoes and genre scenes.` },
      { question: "What subjects did Tiepolo paint?", answer: `Tiepolo painted religious scenes, classical mythology, and allegorical subjects. He often depicted <a href="https://luxurywallart.com/collections/angel-art" target="_blank" rel="noopener"><strong>celestial figures</strong></a> floating in expansive skies.` }
    ]
  },

  "gustave-dore": {
    bioFull: `<p><strong>Gustave Doré</strong> (1832–1883) became the most influential book illustrator of the nineteenth century before turning his ambitions to painting. Born in Strasbourg, he showed prodigious talent from age five. At fifteen, he was already working professionally as a caricaturist for the Parisian satirical magazine <em>Le Journal pour rire</em>. Over the next three decades, he illustrated more than 200 books with over 10,000 engravings. His wood-engraved images for Dante's <em>Divine Comedy</em>, Cervantes' <em>Don Quixote</em>, Milton's <em>Paradise Lost</em>, and the illustrated Bible defined how generations of readers pictured these texts.</p>

<p>Doré's style combined dramatic lighting with dense, crosshatched textures and vast spatial depth. At the height of his career, some forty block-cutters worked to transfer his drawings onto printing blocks. The French government made him a Knight of the Legion of Honour in 1861. His 1867 London exhibition led to the founding of the Doré Gallery on Bond Street, which displayed his large-scale paintings for decades. He also produced bronze and plaster sculptures, including the Alexandre Dumas monument in Paris. Despite his fame as an illustrator, Doré yearned for recognition as a serious painter, though critics often dismissed his canvases. He never married and lived with his mother until her death. He died of a heart attack in 1883, aged fifty, while working on illustrations for Shakespeare. His original drawings and prints are held by the <a href="/museum/national-gallery-of-art"><strong>National Gallery of Art</strong></a> in Washington, the British Museum, and the Musée d'Art Moderne in Strasbourg.</p>`,
    faqs: [
      { question: "What was Gustave Doré best known for?", answer: `Doré was the most celebrated <strong>book illustrator</strong> of the 19th century, creating over 10,000 wood engravings for works including Dante's <em>Divine Comedy</em>, the Bible, and <em>Don Quixote</em>.` },
      { question: "Where can I see Gustave Doré's work?", answer: `His prints and drawings are held at the <a href="/museum/national-gallery-of-art"><strong>National Gallery of Art</strong></a> in Washington, the <strong>British Museum</strong> in London, and the Musée d'Art Moderne in Strasbourg.` },
      { question: "What books did Gustave Doré illustrate?", answer: `His most famous illustrations were for Dante's <strong><em>Divine Comedy</em></strong>, Milton's <em>Paradise Lost</em>, Cervantes' <em>Don Quixote</em>, and the illustrated Bible (1866).` },
      { question: "Was Gustave Doré only an illustrator?", answer: `No, Doré also created <strong>large-scale paintings</strong> and sculptures, including the Alexandre Dumas monument in Paris. He longed for recognition as a painter, though critics favored his illustrations.` },
      { question: "When did Gustave Doré start his career?", answer: `Doré began working professionally at <strong>age fifteen</strong> as a caricaturist for <em>Le Journal pour rire</em> in Paris. He was already drawing with remarkable skill by age five.` },
      { question: "How did Gustave Doré create his illustrations?", answer: `Doré drew designs that were transferred to <strong>wood blocks</strong> by teams of engravers. At his peak, some forty block-cutters worked to reproduce his detailed, dramatic compositions.` }
    ]
  },

  "henry-raeburn": {
    bioFull: `<p><strong>Sir Henry Raeburn</strong> (1756–1823) was Scotland's first major painter to build his career at home rather than fleeing south to London. Born in Edinburgh to a yarn manufacturer, he was orphaned young and raised by his older brother. Apprenticed to a goldsmith at fifteen, he taught himself oil painting while decorating jewelry with portrait miniatures. He never had formal artistic training. A brief visit to London brought him advice from Joshua Reynolds, who urged him to study in Rome. Raeburn spent two years in Italy before returning to Edinburgh in 1787, where he remained for the rest of his life.</p>

<p>Raeburn painted directly onto canvas without preparatory drawings, a technique unusual among his contemporaries. His bold, vigorous brushwork, sometimes called his "square touch," captured Highland chiefs, lawyers, professors, and literary figures of the Scottish Enlightenment with psychological depth and energy. He completed over a thousand portraits in his fifty-year career. Financial troubles led to bankruptcy in 1808, but he recovered. In 1822, during King George IV's celebrated visit to Scotland, Raeburn received a knighthood at Hopetoun House and was appointed His Majesty's Limner for Scotland. He died the following year. His best-known painting today, <em>The Skating Minister</em> (Reverend Robert Walker on Duddingston Loch), was nearly unknown until acquired by the <a href="/museum/national-gallery-of-scotland"><strong>National Galleries of Scotland</strong></a> in 1949. More of his work hangs at the <a href="/museum/met"><strong>Metropolitan Museum of Art</strong></a> and <a href="/museum/national-gallery"><strong>National Gallery</strong></a> in London.</p>`,
    faqs: [
      { question: "What was Henry Raeburn known for?", answer: `Raeburn was Scotland's leading <strong>portrait painter</strong> during the late 18th and early 19th centuries. He painted over a thousand portraits of Scottish society figures without ever leaving Edinburgh.` },
      { question: "Where can I see Henry Raeburn's paintings?", answer: `Major collections are at the <a href="/museum/national-gallery-of-scotland"><strong>National Galleries of Scotland</strong></a> in Edinburgh, the <a href="/museum/met"><strong>Metropolitan Museum of Art</strong></a>, and the <a href="/museum/national-gallery"><strong>National Gallery</strong></a> in London.` },
      { question: "What is Henry Raeburn's most famous painting?", answer: `<em>The Skating Minister</em> (Rev. Robert Walker Skating on Duddingston Loch) is his best-known work today. It was nearly <strong>unknown until 1949</strong> when Scotland's National Gallery acquired it.` },
      { question: "Did Henry Raeburn have formal art training?", answer: `No, Raeburn was <strong>entirely self-taught</strong>. He began by painting miniatures on jewelry during his goldsmith apprenticeship and never attended an art academy.` },
      { question: "What was Raeburn's painting technique?", answer: `Raeburn painted <strong>directly on canvas without preliminary drawings</strong>, using bold, vigorous brushwork that contemporaries called his "square touch."` },
      { question: "Why is Henry Raeburn historically significant?", answer: `Raeburn was the <strong>first major Scottish painter</strong> to build his entire career in Scotland rather than moving to London, creating a visual record of the Scottish Enlightenment.` }
    ]
  },

  "joshua-reynolds": {
    bioFull: `<p><strong>Sir Joshua Reynolds</strong> (1723–1792) raised English portrait painting to a level of intellectual ambition it had never before achieved. Born in Devon, the son of a grammar school master, he apprenticed with the fashionable portraitist Thomas Hudson before spending three years in Italy studying the Old Masters. He returned determined to apply what he called the "Grand Manner," borrowing poses, compositions, and symbolism from Raphael, Michelangelo, and classical antiquity to elevate portraiture above mere likeness.</p>

<p>In 1768, Reynolds became the founding president of the Royal Academy of Arts, a position he held until his death. King George III knighted him the following year. His annual lectures at the Academy, later published as the <em>Discourses on Art</em>, influenced generations of British artists and helped establish a theoretical framework for fine art in England. His studio was extraordinarily productive, completing over 2,000 paintings, though assistants handled much of the drapery work. Famous sitters included Samuel Johnson, Edmund Burke, the actress Sarah Siddons, and the Tahitian visitor Omai. His <em>Portrait of Omai</em> has been called "one of the greatest things British art has ever produced." Reynolds' eyesight began failing in 1789, and he delivered his last Discourse in 1790. He died in 1792 and was buried in St. Paul's Cathedral after lying in state at the Royal Academy. His works hang at the <a href="/museum/tate-modern"><strong>Tate Britain</strong></a>, the <a href="/museum/national-gallery"><strong>National Gallery</strong></a>, and the <a href="/museum/met"><strong>Metropolitan Museum of Art</strong></a>.</p>`,
    faqs: [
      { question: "What was Joshua Reynolds known for?", answer: `Reynolds was the leading English <strong>portrait painter</strong> of the 18th century and the founder of the Royal Academy of Arts. He pioneered the "Grand Manner" style in British portraiture.` },
      { question: "Where can I see Joshua Reynolds' paintings?", answer: `Major works are at <a href="/museum/tate-modern"><strong>Tate Britain</strong></a>, the <a href="/museum/national-gallery"><strong>National Gallery</strong></a> in London, and the <a href="/museum/met"><strong>Metropolitan Museum of Art</strong></a> in New York.` },
      { question: "What was the Grand Manner in painting?", answer: `Reynolds' <strong>Grand Manner</strong> borrowed poses and symbolism from classical antiquity and Renaissance masters like Raphael to give portraits heroic, intellectual weight.` },
      { question: "What were Joshua Reynolds' Discourses?", answer: `The <em>Discourses on Art</em> were <strong>fifteen lectures</strong> Reynolds delivered as Royal Academy president between 1769 and 1790. They shaped British art theory for generations.` },
      { question: "Who were Joshua Reynolds' famous sitters?", answer: `Reynolds painted <strong>Samuel Johnson</strong>, Edmund Burke, the actress Sarah Siddons, and the Tahitian visitor Omai. His studio produced over 2,000 portraits.` },
      { question: "When did Joshua Reynolds found the Royal Academy?", answer: `Reynolds became the <strong>founding president of the Royal Academy</strong> in 1768. King George III knighted him the following year.` }
    ]
  },

  "matthias-grunewald": {
    bioFull: `<p><strong>Matthias Grünewald</strong> (c. 1470–1528) created the most emotionally intense religious paintings of the German <a href="/movement/northern-renaissance"><strong>Northern Renaissance</strong></a>. His real name was Mathis Gothart Nithart; "Grünewald" was invented by a 17th-century biographer. Unlike his contemporary Albrecht Dürer, who embraced Italian Renaissance ideals, Grünewald stayed rooted in the Gothic tradition. His figures writhe with agony, his colors blaze with supernatural intensity, and his religious scenes carry a visceral spiritual charge that later influenced German <a href="/movement/expressionism"><strong>Expressionists</strong></a>.</p>

<p>His masterpiece is the Isenheim Altarpiece (1512–1516), created for a hospital run by the Antonite Order in Alsace. The monks treated patients suffering from ergotism, a gangrenous skin disease caused by fungus-infected rye. Grünewald's Crucifixion panel shows Christ's body covered in wounds and sores, designed to speak directly to the suffering of the sick. The altarpiece has multiple hinged panels that open to reveal different scenes, including an Annunciation, Resurrection, and Concert of Angels. Around 1516, Grünewald entered the service of Cardinal Albrecht of Mainz. He lost this position in 1526, apparently due to sympathy with the Peasants' Revolt. He spent his final years in Protestant-leaning cities, working as a hydraulic engineer in Halle, where he died in 1528. Only ten paintings and thirty-five drawings survive. The Isenheim Altarpiece remains at the <a href="/museum/musee-unterlinden"><strong>Musée Unterlinden</strong></a> in Colmar, France.</p>`,
    faqs: [
      { question: "What is Matthias Grünewald's most famous work?", answer: `The <strong>Isenheim Altarpiece</strong> (1512–1516) is his masterpiece. Created for a hospital in Alsace, its visceral Crucifixion spoke directly to patients suffering from skin disease.` },
      { question: "Where can I see Matthias Grünewald's work?", answer: `The Isenheim Altarpiece is at the <a href="/museum/musee-unterlinden"><strong>Musée Unterlinden</strong></a> in Colmar, France. His surviving works are extremely rare, with only ten paintings known.` },
      { question: "What art movement was Matthias Grünewald part of?", answer: `Grünewald worked during the <a href="/movement/northern-renaissance"><strong>Northern Renaissance</strong></a> but rejected Italian classical ideals, staying rooted in Gothic emotional intensity.` },
      { question: "How did Grünewald influence later artists?", answer: `His emotionally raw religious imagery and intense colors directly influenced German <a href="/movement/expressionism"><strong>Expressionists</strong></a> in the early 20th century.` },
      { question: "What was Grünewald's real name?", answer: `His actual name was <strong>Mathis Gothart Nithart</strong>. The name "Grünewald" was mistakenly given to him by a 17th-century biographer.` },
      { question: "What subjects did Matthias Grünewald paint?", answer: `Grünewald painted exclusively <a href="https://luxurywallart.com/collections/spiritual-art" target="_blank" rel="noopener"><strong>religious subjects</strong></a>: Crucifixions, saints, angels, and scenes from the life of Christ with intense spiritual emotion.` }
    ]
  },

  "simon-vouet": {
    bioFull: `<p><strong>Simon Vouet</strong> (1590–1649) brought Italian <a href="/movement/baroque"><strong>Baroque</strong></a> painting to France and shaped the next generation of French artists. Born in Paris to a painter father, he started as a portrait painter and traveled to Constantinople at age fourteen to complete a commissioned portrait. By 1614 he had settled in Rome, where he absorbed the dramatic chiaroscuro of Caravaggio before developing a lighter, more decorative style influenced by Veronese. His success was so great that the Accademia di San Luca elected him president in 1624.</p>

<p>In 1627, King Louis XIII summoned Vouet back to Paris as Premier Peintre du Roi (First Painter to the King). For the next two decades, he dominated French painting. Royal commissions poured in for the Louvre, the Palais du Luxembourg, and the Château de Saint-Germain-en-Laye. Cardinal Richelieu hired him to decorate the Palais-Royal. Vouet ran a large workshop that trained many of the artists who would define French painting for the next generation, including Charles Le Brun, who later organized all decorative painting at Versailles. Vouet's wife Virginia da Vezzo was also a painter, as were his brother Aubin, his son Louis-René, and his sons-in-law Michel Dorigny and François Tortebat. Vouet was both prolific and versatile, creating altarpieces, mythological scenes, portraits, and decorative schemes. He died in Paris in 1649. His paintings can be found at the <a href="/museum/louvre"><strong>Louvre</strong></a>, the <a href="/museum/national-gallery"><strong>National Gallery</strong></a> in London, and the Palazzo Barberini in Rome.</p>`,
    faqs: [
      { question: "What art movement was Simon Vouet part of?", answer: `Vouet was a leading <a href="/movement/baroque"><strong>Baroque</strong></a> painter who brought Italian styles to France. He began as a Caravaggist before developing a lighter, more decorative approach.` },
      { question: "Where can I see Simon Vouet's paintings?", answer: `Major works hang at the <a href="/museum/louvre"><strong>Louvre</strong></a> in Paris, the <a href="/museum/national-gallery"><strong>National Gallery</strong></a> in London, and the Palazzo Barberini in Rome.` },
      { question: "Who were Simon Vouet's famous students?", answer: `His most influential pupil was <strong>Charles Le Brun</strong>, who later directed all decorative painting at Versailles and defined the official style of Louis XIV's court.` },
      { question: "What position did Simon Vouet hold in France?", answer: `Louis XIII appointed him <strong>Premier Peintre du Roi</strong> (First Painter to the King) in 1627. He dominated French painting for over two decades.` },
      { question: "Was painting a family profession for Vouet?", answer: `Yes, his father, brother, wife, son, and <strong>two sons-in-law</strong> were all painters. His wife Virginia da Vezzo had her own painting career.` },
      { question: "What was Vouet's achievement in Rome?", answer: `Vouet was so successful in Rome that the <strong>Accademia di San Luca</strong> elected him president in 1624, a rare honor for a foreign artist.` }
    ]
  },

  "thomas-eakins": {
    bioFull: `<p><strong>Thomas Eakins</strong> (1844–1916) pushed <a href="/movement/american-realism"><strong>American Realism</strong></a> to its most unflinching heights. Born in Philadelphia, the son of a calligraphy teacher, he studied at the Pennsylvania Academy of the Fine Arts before training in Paris under Jean-Léon Gérôme at the École des Beaux-Arts. A six-month tour of Spain deepened his admiration for Velázquez and Ribera. He returned to Philadelphia in 1870 and rarely left again, spending four decades painting the people of his hometown with rigorous honesty.</p>

<p>Eakins painted several hundred portraits of friends, family, doctors, scientists, and clergymen. His most famous works are <em>The Gross Clinic</em> (1875) and <em>The Agnew Clinic</em> (1889), which show surgeons operating in graphic detail. Rowing scenes like <em>Max Schmitt in a Single Scull</em> demonstrate his obsession with anatomy and perspective. He began teaching at the Pennsylvania Academy in 1876 and transformed it into America's leading art school. In 1886, he was forced to resign after removing a male model's loincloth during a lecture to female students. This scandal damaged his reputation, and he sold few paintings during his lifetime. He married his former student Susan Hannah Macdowell in 1884. Eakins also worked as a photographer and sculptor. He died in 1916, still largely unrecognized. Since then, historians have called him "the strongest, most profound realist in nineteenth- and early-twentieth-century American art." His work hangs at the <a href="/museum/met"><strong>Metropolitan Museum of Art</strong></a>, the <a href="/museum/art-institute-chicago"><strong>Art Institute of Chicago</strong></a>, and the <a href="/museum/musee-dorsay"><strong>Musée d'Orsay</strong></a>.</p>`,
    faqs: [
      { question: "What art movement was Thomas Eakins part of?", answer: `Eakins was a leading figure in <a href="/movement/american-realism"><strong>American Realism</strong></a>, known for painting people and scenes with unflinching honesty and scientific precision.` },
      { question: "Where can I see Thomas Eakins' paintings?", answer: `Major works are at the <a href="/museum/met"><strong>Metropolitan Museum of Art</strong></a>, the <a href="/museum/art-institute-chicago"><strong>Art Institute of Chicago</strong></a>, and the Philadelphia Museum of Art.` },
      { question: "What are Thomas Eakins' most famous paintings?", answer: `<em>The Gross Clinic</em> (1875) and <em>The Agnew Clinic</em> (1889), showing surgeons operating in graphic detail, are his most celebrated works.` },
      { question: "Why was Thomas Eakins forced to resign from teaching?", answer: `In 1886, Eakins removed a <strong>male model's loincloth</strong> during a lecture attended by female students. The resulting scandal forced his resignation from the Pennsylvania Academy.` },
      { question: "Did Thomas Eakins receive recognition during his lifetime?", answer: `No, Eakins sold few paintings and remained largely <strong>unrecognized until after his death</strong>. Historians now consider him America's greatest realist painter.` },
      { question: "What subjects did Thomas Eakins paint?", answer: `Eakins painted <a href="https://luxurywallart.com/collections/portrait-art" target="_blank" rel="noopener"><strong>portraits</strong></a>, surgical scenes, rowing, boxing, and everyday Philadelphia life with scientific attention to anatomy and perspective.` }
    ]
  },

  "vilhelm-hammershoi": {
    bioFull: `<p><strong>Vilhelm Hammershøi</strong> (1864–1916) became Denmark's poet of quiet, empty rooms. Born in Copenhagen to a merchant family, he studied drawing from age eight and later trained at the Royal Danish Academy of Fine Arts and under Peder Severin Krøyer. When he debuted at the Charlottenborg Spring Exhibition in 1885, Pierre-Auguste Renoir reportedly admired his portrait of his sister Anna. Yet Hammershøi's mature style would reject the bright colors of Impressionism in favor of a muted palette of grays, desaturated greens, and soft <a href="https://luxurywallart.com/collections/neutral-art" target="_blank" rel="noopener"><strong>neutral tones</strong></a>.</p>

<p>He is best known for his <a href="https://luxurywallart.com/collections/minimalist-art" target="_blank" rel="noopener"><strong>interior scenes</strong></a>, most painted in his Copenhagen apartments at Strandgade 30 (1898–1909) and Strandgade 25 (1913–1916). His wife Ida appears frequently, almost always from behind, absorbed in something the viewer cannot share. The rooms are spare, the light subdued, the atmosphere poetic and melancholic. His work has been compared to Vermeer, though stripped of Vermeer's warmth. He also painted austere Danish landscapes and architectural studies of London shrouded in coal-smoke fog. Artists and writers including Emil Nolde and Rainer Maria Rilke sought him out, noting his shy, retiring manner. Hammershøi died of throat cancer in 1916, only fifty-one years old. His reputation faded until a 1982 Brooklyn Museum exhibition brought him international attention. In 2008, the Royal Academy of London hosted "Vilhelm Hammershøi: The Poetry of Silence." His work hangs at the <a href="/museum/met"><strong>Metropolitan Museum of Art</strong></a>, <a href="/museum/tate-modern"><strong>Tate</strong></a>, and the National Gallery of Denmark.</p>`,
    faqs: [
      { question: "What was Vilhelm Hammershøi known for painting?", answer: `Hammershøi is celebrated for his quiet, melancholic <strong>interior scenes</strong>. Most depict spare Copenhagen rooms with subdued light and his wife Ida seen from behind.` },
      { question: "Where can I see Vilhelm Hammershøi's paintings?", answer: `His work is at the <a href="/museum/met"><strong>Metropolitan Museum of Art</strong></a>, <a href="/museum/tate-modern"><strong>Tate</strong></a> in London, and the <strong>National Gallery of Denmark</strong> in Copenhagen.` },
      { question: "What colors did Hammershøi use?", answer: `Hammershøi worked with a limited palette of <a href="https://luxurywallart.com/collections/grey-art" target="_blank" rel="noopener"><strong>grays</strong></a>, desaturated yellows, greens, and muted neutral tones, rejecting the bright colors of Impressionism.` },
      { question: "Why is Hammershøi called the painter of tranquil rooms?", answer: `His interiors capture a distinctive atmosphere of <strong>silence and stillness</strong>. Figures often face away from the viewer, absorbed in thoughts we cannot access.` },
      { question: "When did Hammershøi gain international recognition?", answer: `Though respected in Scandinavia, he remained largely unknown abroad until a <strong>1982 Brooklyn Museum</strong> exhibition introduced him to international audiences.` },
      { question: "Who admired Vilhelm Hammershøi's work?", answer: `Artists and writers including <strong>Emil Nolde</strong> and poet <strong>Rainer Maria Rilke</strong> sought him out. Renoir reportedly admired his early portrait of his sister.` }
    ]
  },

  "andre-derain": {
    bioFull: `<p><strong>André Derain</strong> (1880–1954) helped launch <a href="/movement/fauvism"><strong>Fauvism</strong></a> alongside Henri Matisse, though his restless experimentation soon carried him in other directions. Born in Chatou near Paris, he studied engineering while painting in his spare time. In 1900, he met Matisse on a train and began sharing a studio with Maurice de Vlaminck. Military service interrupted his work until 1904, when Matisse persuaded Derain's parents to let him pursue art full-time. The following summer, Derain and Matisse painted together in the Mediterranean village of Collioure, producing the explosive <a href="https://luxurywallart.com/collections/colorful-artwork" target="_blank" rel="noopener"><strong>color</strong></a> experiments that would scandalize the 1905 Salon d'Automne and earn them the name "les Fauves" (wild beasts).</p>

<p>In 1906, dealer Ambroise Vollard sent Derain to London, where he produced thirty radically colored views of the Thames, Westminster, and Hyde Park. These paintings mark the height of his Fauvist period. Soon after, Derain fell in with Picasso and Braque in Montmartre and became fascinated by African art and <a href="/movement/cubism"><strong>Cubism</strong></a>. After World War I, he turned toward classical restraint and was praised as a leader of the renewed traditionalism. He designed sets for Diaghilev's Ballets Russes in 1919 and won the Carnegie Prize in 1928. During the German occupation, Derain accepted an invitation to visit Nazi Germany in 1941, a decision that led to accusations of collaboration and damaged his reputation after liberation. He was struck by a car and died in 1954. His Fauvist paintings hang at the <a href="/museum/tate-modern"><strong>Tate Modern</strong></a>, the <a href="/museum/moma"><strong>Museum of Modern Art</strong></a>, and the <a href="/museum/musee-dorsay"><strong>Musée d'Orsay</strong></a>.</p>`,
    faqs: [
      { question: "What art movement was André Derain part of?", answer: `Derain co-founded <a href="/movement/fauvism"><strong>Fauvism</strong></a> with Henri Matisse in 1905. He later experimented with <a href="/movement/cubism"><strong>Cubism</strong></a> and eventually turned to classical traditionalism.` },
      { question: "Where can I see André Derain's paintings?", answer: `His Fauvist works are at the <a href="/museum/tate-modern"><strong>Tate Modern</strong></a> in London, the <a href="/museum/moma"><strong>Museum of Modern Art</strong></a> in New York, and the <a href="/museum/musee-dorsay"><strong>Musée d'Orsay</strong></a> in Paris.` },
      { question: "What was the origin of the term Fauvism?", answer: `Critic Louis Vauxcelles called Derain and Matisse <strong>"les Fauves" (wild beasts)</strong> at the 1905 Salon d'Automne, shocked by their vivid, unnatural colors.` },
      { question: "What are Derain's most famous paintings?", answer: `His <strong>London series</strong> (1906), showing the Thames and Big Ben in explosive Fauvist colors, represents the peak of his early career.` },
      { question: "Why was André Derain's later reputation damaged?", answer: `Derain accepted an invitation to visit <strong>Nazi Germany in 1941</strong>. After liberation, he was accused of collaboration and ostracized by former supporters.` },
      { question: "Who did André Derain work with?", answer: `He painted with <strong>Matisse</strong> at Collioure and later befriended <strong>Picasso and Braque</strong> in Montmartre, where he developed an interest in Cubism and African art.` }
    ]
  }
};

async function main() {
  console.log("Updating artists batch 6 (10 artists)...\n");

  let updated = 0;
  for (const [slug, data] of Object.entries(artistUpdates)) {
    const artist = await prisma.artist.findUnique({ where: { slug } });
    if (artist) {
      await prisma.artist.update({
        where: { slug },
        data: {
          bioFull: data.bioFull,
          faqs: data.faqs,
          updatedAt: new Date()
        }
      });
      console.log(`✓ Updated: ${artist.name}`);
      updated++;
    } else {
      console.log(`✗ Not found: ${slug}`);
    }
  }

  console.log(`\nUpdated ${updated} artists in batch 6`);
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
